// Auto-generated by weekly-health-briefing/starter.py
// Deterministic fields. Verdict, bodySignals, connections, actions are appended at runtime.
const PARTIAL_DATA = {
  "window": "Apr 20 \u2014 Apr 26, 2026",
  "window_start": "2026-04-20",
  "window_end": "2026-04-26",
  "generated_at": "2026-05-01T07:20:48.814025",
  "weekly_metrics": {
    "hrv_avg": 40.18,
    "hrv_cv": 20.5,
    "hrv_vs_30d_pct": -1.0,
    "hrv_trend": "stable",
    "rhr_avg": 65.67,
    "rhr_vs_30d": 0.7,
    "rhr_trend": "stable",
    "recovery_avg": 53.33,
    "recovery_distribution": {
      "red": 1,
      "amber": 3,
      "green": 2
    },
    "sleep_avg_h": 5.71,
    "deep_avg_h": 1.55,
    "deep_target_h": 1.5,
    "rem_avg_h": 1.6,
    "light_avg_h": 2.56,
    "efficiency_avg": 92.64,
    "sleep_debt_cum_h": 13.7,
    "strain_total": 60.1,
    "strain_recovery_ratio": 1.13,
    "padel_sessions": 4,
    "skin_temp_avg": 34.29,
    "rr_avg": 15.11,
    "supp_compliance": {
      "T3+T4 thyroid medication": "2/2 [critical-med]",
      "Liposomal Glutathione": "2/2",
      "Creatine": "no logs",
      "Magnesium + salt water": "2/2",
      "Digestive enzymes": "2/2",
      "Vit D3+K2": "2/2",
      "B complex": "2/2",
      "Omega 3": "2/2",
      "Shilajit": "2/2",
      "DHEAs": "2/2",
      "Myo inositol + Collagen + EAA Thorne": "2/2",
      "Colostrum": "2/2",
      "Lactoferrin": "2/2",
      "Nato Serra": "2/2",
      "T3 thyroid medication": "2/2 [critical-med]",
      "TMG": "2/2",
      "Zinc": "2/2",
      "Probiotics": "2/2",
      "Magnesium Bisglycinate": "2/2",
      "Black seed oil": "2/2",
      "Detox Binder": "2/2"
    },
    "protein_avg_g": 64,
    "protein_target_hits": 0,
    "alcohol_days": 0,
    "late_dinners": 0,
    "skipped_meals": 0
  },
  "day_summaries": [
    {
      "day": "Mon",
      "date": "2026-04-20",
      "recovery": null,
      "key_event": "\u2014"
    },
    {
      "day": "Tue",
      "date": "2026-04-21",
      "recovery": 72,
      "key_event": "Workout"
    },
    {
      "day": "Wed",
      "date": "2026-04-22",
      "recovery": 49,
      "key_event": "Workout"
    },
    {
      "day": "Thu",
      "date": "2026-04-23",
      "recovery": 47,
      "key_event": "\u2014"
    },
    {
      "day": "Fri",
      "date": "2026-04-24",
      "recovery": 87,
      "key_event": "Workout"
    },
    {
      "day": "Sat",
      "date": "2026-04-25",
      "recovery": 24,
      "key_event": "\u2014"
    },
    {
      "day": "Sun",
      "date": "2026-04-26",
      "recovery": 41,
      "key_event": "\u2014"
    }
  ],
  "daily_macros": {
    "2026-04-20": {
      "cal": null,
      "protein": null,
      "carb": null,
      "fat": null
    },
    "2026-04-21": {
      "cal": null,
      "protein": null,
      "carb": null,
      "fat": null
    },
    "2026-04-22": {
      "cal": null,
      "protein": null,
      "carb": null,
      "fat": null
    },
    "2026-04-23": {
      "cal": null,
      "protein": null,
      "carb": null,
      "fat": null
    },
    "2026-04-24": {
      "cal": null,
      "protein": null,
      "carb": null,
      "fat": null
    },
    "2026-04-25": {
      "cal": 1135,
      "protein": 90,
      "carb": 68,
      "fat": 58
    },
    "2026-04-26": {
      "cal": 1080,
      "protein": 38,
      "carb": 182,
      "fat": 22
    }
  },
  "blood_baselines": {
    "TSH": {
      "value": 6.654,
      "date": "Mar '26",
      "date_iso": "2026-03-01",
      "status": "high"
    },
    "Free T3": {
      "value": 2.92,
      "date": "Mar '26",
      "date_iso": "2026-03-01",
      "status": "in_range"
    },
    "Free T4": {
      "value": 1.11,
      "date": "Mar '26",
      "date_iso": "2026-03-01",
      "status": "in_range"
    },
    "Total T3": {
      "value": 134.0,
      "date": "May '25",
      "date_iso": "2025-05-01",
      "status": "in_range"
    },
    "Total T4": {
      "value": 7.92,
      "date": "May '25",
      "date_iso": "2025-05-01",
      "status": "in_range"
    },
    "Anti-TPO": {
      "value": 354.6,
      "date": "Mar '26",
      "date_iso": "2026-03-01",
      "status": "high"
    },
    "Anti-TG": {
      "value": 13.6,
      "date": "Mar '26",
      "date_iso": "2026-03-01",
      "status": "high"
    },
    "TSH Receptor Ab": {
      "value": 3.11,
      "date": "May '25",
      "date_iso": "2025-05-01",
      "status": "high"
    },
    "Total Testosterone": {
      "value": 205.0,
      "date": "Nov '25",
      "date_iso": "2025-11-01",
      "status": "low"
    },
    "Free Testosterone": {
      "value": 16.8,
      "date": "Nov '25",
      "date_iso": "2025-11-01",
      "status": "in_range"
    },
    "DHEAS": {
      "value": 293.0,
      "date": "Nov '25",
      "date_iso": "2025-11-01",
      "status": "in_range"
    },
    "PSA (Total)": {
      "value": 0.619,
      "date": "Apr '22",
      "date_iso": "2022-04-01",
      "status": null
    },
    "Glucose Fasting": {
      "value": 99.0,
      "date": "Jan '26",
      "date_iso": "2026-01-01",
      "status": null
    },
    "Glucose PP": {
      "value": 103.0,
      "date": "Jan '26",
      "date_iso": "2026-01-01",
      "status": "in_range"
    },
    "HbA1c": {
      "value": 5.6,
      "date": "Jan '26",
      "date_iso": "2026-01-01",
      "status": "in_range"
    },
    "Insulin Fasting": {
      "value": 13.0,
      "date": "Jan '26",
      "date_iso": "2026-01-01",
      "status": null
    },
    "Insulin PP": {
      "value": 45.1,
      "date": "Jan '26",
      "date_iso": "2026-01-01",
      "status": "in_range"
    },
    "C-Peptide": {
      "value": 2.94,
      "date": "Jan '26",
      "date_iso": "2026-01-01",
      "status": null
    },
    "Fructosamine": {
      "value": 251.3,
      "date": "May '25",
      "date_iso": "2025-05-01",
      "status": null
    },
    "Homocysteine": {
      "value": 8.48,
      "date": "Jan '26",
      "date_iso": "2026-01-01",
      "status": "in_range"
    },
    "Total Cholesterol": {
      "value": 223.0,
      "date": "Jan '26",
      "date_iso": "2026-01-01",
      "status": "high"
    },
    "LDL Cholesterol": {
      "value": 156.6,
      "date": "Jan '26",
      "date_iso": "2026-01-01",
      "status": "high"
    },
    "HDL Cholesterol": {
      "value": 41.0,
      "date": "Jan '26",
      "date_iso": "2026-01-01",
      "status": "in_range"
    },
    "Triglycerides": {
      "value": 127.0,
      "date": "Jan '26",
      "date_iso": "2026-01-01",
      "status": null
    },
    "VLDL": {
      "value": 25.4,
      "date": "Jan '26",
      "date_iso": "2026-01-01",
      "status": null
    },
    "Non-HDL Cholesterol": {
      "value": 182.0,
      "date": "Jan '26",
      "date_iso": "2026-01-01",
      "status": null
    },
    "TC/HDL Ratio": {
      "value": 5.4,
      "date": "Jan '26",
      "date_iso": "2026-01-01",
      "status": null
    },
    "LDL/HDL Ratio": {
      "value": 3.8,
      "date": "Jan '26",
      "date_iso": "2026-01-01",
      "status": null
    },
    "Lp(a)": {
      "value": 14.6,
      "date": "Nov '25",
      "date_iso": "2025-11-01",
      "status": "in_range"
    },
    "LP-PLA2": {
      "value": 128.0,
      "date": "May '25",
      "date_iso": "2025-05-01",
      "status": null
    },
    "ApoA1": {
      "value": 147.0,
      "date": "Nov '25",
      "date_iso": "2025-11-01",
      "status": null
    },
    "ApoB": {
      "value": 132.0,
      "date": "Nov '25",
      "date_iso": "2025-11-01",
      "status": "in_range"
    },
    "ALT (SGPT)": {
      "value": 39.0,
      "date": "Jan '26",
      "date_iso": "2026-01-01",
      "status": "in_range"
    },
    "AST (SGOT)": {
      "value": 26.0,
      "date": "Jan '26",
      "date_iso": "2026-01-01",
      "status": "in_range"
    },
    "ALP": {
      "value": 86.0,
      "date": "Jan '26",
      "date_iso": "2026-01-01",
      "status": "in_range"
    },
    "GGT": {
      "value": 42.0,
      "date": "Jan '26",
      "date_iso": "2026-01-01",
      "status": "in_range"
    },
    "Bilirubin Total": {
      "value": 0.94,
      "date": "Jan '26",
      "date_iso": "2026-01-01",
      "status": "in_range"
    },
    "Bilirubin Direct": {
      "value": 0.35,
      "date": "Jan '26",
      "date_iso": "2026-01-01",
      "status": "high"
    },
    "Bilirubin Indirect": {
      "value": 0.59,
      "date": "Jan '26",
      "date_iso": "2026-01-01",
      "status": "in_range"
    },
    "LDH": {
      "value": 165.0,
      "date": "Jan '26",
      "date_iso": "2026-01-01",
      "status": "in_range"
    },
    "Total Protein": {
      "value": 7.7,
      "date": "Jan '26",
      "date_iso": "2026-01-01",
      "status": "in_range"
    },
    "Albumin": {
      "value": 4.5,
      "date": "Jan '26",
      "date_iso": "2026-01-01",
      "status": "in_range"
    },
    "Globulin": {
      "value": 3.2,
      "date": "Jan '26",
      "date_iso": "2026-01-01",
      "status": "in_range"
    },
    "A/G Ratio": {
      "value": 1.4,
      "date": "Jan '26",
      "date_iso": "2026-01-01",
      "status": "in_range"
    },
    "Creatinine": {
      "value": 0.77,
      "date": "Jan '26",
      "date_iso": "2026-01-01",
      "status": "in_range"
    },
    "BUN": {
      "value": 16.8,
      "date": "Jan '26",
      "date_iso": "2026-01-01",
      "status": "in_range"
    },
    "Urea": {
      "value": 36.0,
      "date": "Jan '26",
      "date_iso": "2026-01-01",
      "status": "in_range"
    },
    "Uric Acid": {
      "value": 5.6,
      "date": "Jan '26",
      "date_iso": "2026-01-01",
      "status": "in_range"
    },
    "eGFR": {
      "value": 114.0,
      "date": "Jan '26",
      "date_iso": "2026-01-01",
      "status": "in_range"
    },
    "Cystatin C": {
      "value": 0.81,
      "date": "May '25",
      "date_iso": "2025-05-01",
      "status": null
    },
    "Hemoglobin": {
      "value": 15.4,
      "date": "Jan '26",
      "date_iso": "2026-01-01",
      "status": "in_range"
    },
    "RBC": {
      "value": 5.04,
      "date": "Jan '26",
      "date_iso": "2026-01-01",
      "status": "in_range"
    },
    "Hematocrit (PCV)": {
      "value": 46.4,
      "date": "Jan '26",
      "date_iso": "2026-01-01",
      "status": "in_range"
    },
    "MCV": {
      "value": 92.0,
      "date": "Jan '26",
      "date_iso": "2026-01-01",
      "status": "in_range"
    },
    "MCH": {
      "value": 30.5,
      "date": "Jan '26",
      "date_iso": "2026-01-01",
      "status": "in_range"
    },
    "MCHC": {
      "value": 33.2,
      "date": "Jan '26",
      "date_iso": "2026-01-01",
      "status": "in_range"
    },
    "RDW": {
      "value": 12.7,
      "date": "Jan '26",
      "date_iso": "2026-01-01",
      "status": "in_range"
    },
    "WBC": {
      "value": 6.58,
      "date": "Jan '26",
      "date_iso": "2026-01-01",
      "status": "in_range"
    },
    "Neutrophils %": {
      "value": 50.5,
      "date": "Jan '26",
      "date_iso": "2026-01-01",
      "status": "in_range"
    },
    "Lymphocytes %": {
      "value": 36.8,
      "date": "Jan '26",
      "date_iso": "2026-01-01",
      "status": "in_range"
    },
    "Monocytes %": {
      "value": 6.5,
      "date": "Jan '26",
      "date_iso": "2026-01-01",
      "status": "in_range"
    },
    "Eosinophils %": {
      "value": 6.1,
      "date": "Jan '26",
      "date_iso": "2026-01-01",
      "status": "high"
    },
    "Basophils %": {
      "value": 0.1,
      "date": "Jan '26",
      "date_iso": "2026-01-01",
      "status": "in_range"
    },
    "Platelet Count": {
      "value": 306.0,
      "date": "Jan '26",
      "date_iso": "2026-01-01",
      "status": "in_range"
    },
    "MPV": {
      "value": 11.1,
      "date": "Jan '26",
      "date_iso": "2026-01-01",
      "status": "high"
    },
    "ESR": {
      "value": 22.0,
      "date": "Jan '26",
      "date_iso": "2026-01-01",
      "status": "high"
    },
    "Serum Iron": {
      "value": 119.0,
      "date": "Jan '26",
      "date_iso": "2026-01-01",
      "status": "in_range"
    },
    "TIBC": {
      "value": 329.0,
      "date": "Jan '26",
      "date_iso": "2026-01-01",
      "status": "in_range"
    },
    "Transferrin Saturation": {
      "value": 36.0,
      "date": "Jan '26",
      "date_iso": "2026-01-01",
      "status": "in_range"
    },
    "Ferritin": {
      "value": 51.3,
      "date": "Jan '26",
      "date_iso": "2026-01-01",
      "status": "in_range"
    },
    "UIBC": {
      "value": 210.0,
      "date": "Jan '26",
      "date_iso": "2026-01-01",
      "status": "in_range"
    },
    "Vitamin D (25-OH)": {
      "value": 46.6,
      "date": "Jan '26",
      "date_iso": "2026-01-01",
      "status": "in_range"
    },
    "Vitamin B12": {
      "value": 411.0,
      "date": "Jan '26",
      "date_iso": "2026-01-01",
      "status": "in_range"
    },
    "Vitamin A": {
      "value": 668.38,
      "date": "May '25",
      "date_iso": "2025-05-01",
      "status": "in_range"
    },
    "Vitamin E": {
      "value": 10844.0,
      "date": "May '25",
      "date_iso": "2025-05-01",
      "status": "in_range"
    },
    "Vitamin K": {
      "value": 0.17,
      "date": "May '25",
      "date_iso": "2025-05-01",
      "status": "in_range"
    },
    "Vitamin B1 (Thiamin)": {
      "value": 0.78,
      "date": "May '25",
      "date_iso": "2025-05-01",
      "status": "in_range"
    },
    "Vitamin B2 (Riboflavin)": {
      "value": 9.77,
      "date": "May '25",
      "date_iso": "2025-05-01",
      "status": "in_range"
    },
    "Vitamin B3 (Nicotinic)": {
      "value": 1.38,
      "date": "May '25",
      "date_iso": "2025-05-01",
      "status": "in_range"
    },
    "Vitamin B5 (Pantothenic)": {
      "value": 73.74,
      "date": "May '25",
      "date_iso": "2025-05-01",
      "status": "in_range"
    },
    "Vitamin B6 (P5P)": {
      "value": 13.24,
      "date": "May '25",
      "date_iso": "2025-05-01",
      "status": "in_range"
    },
    "Vitamin B7 (Biotin)": {
      "value": 3.79,
      "date": "May '25",
      "date_iso": "2025-05-01",
      "status": "high"
    },
    "Vitamin B9 (Folic Acid)": {
      "value": 0.49,
      "date": "May '25",
      "date_iso": "2025-05-01",
      "status": "in_range"
    },
    "Sodium": {
      "value": 144.0,
      "date": "Jan '26",
      "date_iso": "2026-01-01",
      "status": "in_range"
    },
    "Potassium": {
      "value": 5.1,
      "date": "Jan '26",
      "date_iso": "2026-01-01",
      "status": "in_range"
    },
    "Chloride": {
      "value": 104.0,
      "date": "Jan '26",
      "date_iso": "2026-01-01",
      "status": "in_range"
    },
    "Calcium": {
      "value": 10.1,
      "date": "Jan '26",
      "date_iso": "2026-01-01",
      "status": "in_range"
    },
    "Magnesium": {
      "value": 1.9,
      "date": "Jan '26",
      "date_iso": "2026-01-01",
      "status": "in_range"
    },
    "Phosphorus": {
      "value": 4.3,
      "date": "Jan '26",
      "date_iso": "2026-01-01",
      "status": "in_range"
    },
    "Bicarbonate": {
      "value": 24.4,
      "date": "Jun '23",
      "date_iso": "2023-06-01",
      "status": "in_range"
    },
    "Selenium": {
      "value": 198.86,
      "date": "May '25",
      "date_iso": "2025-05-01",
      "status": "high"
    },
    "hs-CRP": {
      "value": 1.545,
      "date": "Jan '26",
      "date_iso": "2026-01-01",
      "status": "in_range"
    },
    "Anti-CCP (ACCP)": {
      "value": 0.5,
      "date": "May '25",
      "date_iso": "2025-05-01",
      "status": "in_range"
    },
    "ANA": {
      "value": 7.16,
      "date": "May '25",
      "date_iso": "2025-05-01",
      "status": "in_range"
    },
    "Alpha-1-Antitrypsin": {
      "value": 126.7,
      "date": "May '25",
      "date_iso": "2025-05-01",
      "status": "in_range"
    },
    "Amylase": {
      "value": 64.4,
      "date": "May '25",
      "date_iso": "2025-05-01",
      "status": "in_range"
    },
    "Lipase": {
      "value": 27.8,
      "date": "May '25",
      "date_iso": "2025-05-01",
      "status": "in_range"
    },
    "EHEC (Enterohemorrhagic E. coli)": {
      "value": 8.79,
      "date": "May 2025",
      "date_iso": "2025-05-01",
      "status": "high"
    },
    "Blastocystis hominis": {
      "value": 2.7,
      "date": "May 2025",
      "date_iso": "2025-05-01",
      "status": "high"
    },
    "Bacteroides fragilis": {
      "value": 2.17,
      "date": "May 2025",
      "date_iso": "2025-05-01",
      "status": "in_range"
    },
    "Bifidobacterium spp.": {
      "value": 6.3,
      "date": "May 2025",
      "date_iso": "2025-05-01",
      "status": "low"
    },
    "Enterococcus spp.": {
      "value": 3.61,
      "date": "May 2025",
      "date_iso": "2025-05-01",
      "status": "in_range"
    },
    "Escherichia spp.": {
      "value": 6.19,
      "date": "May 2025",
      "date_iso": "2025-05-01",
      "status": "high"
    },
    "Lactobacillus spp.": {
      "value": 7.43,
      "date": "May 2025",
      "date_iso": "2025-05-01",
      "status": "low"
    },
    "Enterobacter spp.": {
      "value": 6.41,
      "date": "May 2025",
      "date_iso": "2025-05-01",
      "status": "high"
    },
    "Akkermansia muciniphila": {
      "value": 1.0,
      "date": "May 2025",
      "date_iso": "2025-05-01",
      "status": "in_range"
    },
    "Faecalibacterium prausnitzii": {
      "value": 2.21,
      "date": "May 2025",
      "date_iso": "2025-05-01",
      "status": "in_range"
    },
    "Roseburia spp.": {
      "value": 1.62,
      "date": "May 2025",
      "date_iso": "2025-05-01",
      "status": "low"
    },
    "Pseudomonas spp.": {
      "value": 1.22,
      "date": "May 2025",
      "date_iso": "2025-05-01",
      "status": "high"
    },
    "Pseudomonas aeruginosa": {
      "value": 4.72,
      "date": "May 2025",
      "date_iso": "2025-05-01",
      "status": "in_range"
    },
    "Klebsiella spp.": {
      "value": 1.56,
      "date": "May 2025",
      "date_iso": "2025-05-01",
      "status": "in_range"
    },
    "Klebsiella pneumoniae": {
      "value": 1.71,
      "date": "May 2025",
      "date_iso": "2025-05-01",
      "status": "in_range"
    },
    "Streptococcus spp.": {
      "value": 9.73,
      "date": "May 2025",
      "date_iso": "2025-05-01",
      "status": "high"
    },
    "Bacillus spp.": {
      "value": 3.61,
      "date": "May 2025",
      "date_iso": "2025-05-01",
      "status": "high"
    },
    "Enterococcus faecium": {
      "value": 6.11,
      "date": "May 2025",
      "date_iso": "2025-05-01",
      "status": "high"
    },
    "Staphylococcus aureus": {
      "value": 1.75,
      "date": "May 2025",
      "date_iso": "2025-05-01",
      "status": "in_range"
    },
    "Citrobacter freundii": {
      "value": 4.6,
      "date": "May 2025",
      "date_iso": "2025-05-01",
      "status": "in_range"
    },
    "Fusobacterium spp.": {
      "value": 2.49,
      "date": "May 2025",
      "date_iso": "2025-05-01",
      "status": "high"
    },
    "Prevotella spp.": {
      "value": 5.59,
      "date": "May 2025",
      "date_iso": "2025-05-01",
      "status": "high"
    },
    "Bacteroidetes": {
      "value": 1.61,
      "date": "May 2025",
      "date_iso": "2025-05-01",
      "status": "low"
    },
    "Firmicutes": {
      "value": 6.05,
      "date": "May 2025",
      "date_iso": "2025-05-01",
      "status": "in_range"
    },
    "Firmicutes:Bacteroidetes": {
      "value": 0.37,
      "date": "May 2025",
      "date_iso": "2025-05-01",
      "status": "in_range"
    },
    "Elastase-1": {
      "value": 109.0,
      "date": "May 2025",
      "date_iso": "2025-05-01",
      "status": "low"
    },
    "\u03b2-Glucuronidase": {
      "value": 2147.0,
      "date": "May 2025",
      "date_iso": "2025-05-01",
      "status": "in_range"
    },
    "Occult Blood (FIT)": {
      "value": 0.0,
      "date": "May 2025",
      "date_iso": "2025-05-01",
      "status": "in_range"
    },
    "Secretory IgA": {
      "value": 210.0,
      "date": "May 2025",
      "date_iso": "2025-05-01",
      "status": "low"
    },
    "Anti-gliadin IgA": {
      "value": 24.0,
      "date": "May 2025",
      "date_iso": "2025-05-01",
      "status": "in_range"
    },
    "Calprotectin": {
      "value": 0.0,
      "date": "May 2025",
      "date_iso": "2025-05-01",
      "status": "in_range"
    },
    "Eosinophil Activation (EDN)": {
      "value": 0.54,
      "date": "May 2025",
      "date_iso": "2025-05-01",
      "status": "in_range"
    },
    "Zonulin": {
      "value": 22.1,
      "date": "May 2025",
      "date_iso": "2025-05-01",
      "status": "in_range"
    },
    "pH": {
      "value": 6.0,
      "date": "May '25",
      "date_iso": "2025-05-01",
      "status": null
    },
    "Specific Gravity": {
      "value": 1.015,
      "date": "May '25",
      "date_iso": "2025-05-01",
      "status": null
    },
    "Microalbumin": {
      "value": 8.3,
      "date": "May '25",
      "date_iso": "2025-05-01",
      "status": null
    },
    "Urine Creatinine": {
      "value": 65.66,
      "date": "May '25",
      "date_iso": "2025-05-01",
      "status": null
    },
    "Albumin/Creatinine Ratio": {
      "value": 12.6,
      "date": "May '25",
      "date_iso": "2025-05-01",
      "status": null
    }
  },
  "active_conditions": [
    "Hashimoto's Thyroiditis (autoimmune hypothyroidism)",
    "Low Testosterone (Hypogonadism)",
    "Grade I Fatty Liver",
    "MTHFR A1298C Homozygous Mutation",
    "Borderline Insulin Resistance",
    "Radial Nerve Injury (Right Tricep)"
  ],
  "active_meds": [
    "Thyroid (compounded NDT \u2014 Bella Sante)",
    "Retatrutide (GLP-1/GIP/glucagon triple agonist)"
  ],
  "treatment_goals": [
    "TSH",
    "Total Testosterone",
    "Body Weight",
    "Body Fat %",
    "Muscle Mass",
    "Fatty Liver",
    "Gut Health"
  ],
  "active_concerns": [
    "Weight trajectory",
    "HRV",
    "Sleep",
    "Body composition",
    "TSH improvement",
    "Testosterone trajectory",
    "Strength capacity",
    "Retatrutide effects",
    "Liver markers",
    "Insulin resistance"
  ],
  "baselines_30d_90d": {
    "hrv_30d_avg": 40.58,
    "hrv_p5": 22.36,
    "hrv_p95": 51.72,
    "rhr_30d_avg": 64.95,
    "rhr_p5": 61,
    "rhr_p95": 77,
    "recovery_30d_avg": 46.64,
    "recovery_p5": 16,
    "recovery_p95": 85,
    "sleep_total_h_30d_avg": 5.41,
    "sleep_total_h_p5": 3.54,
    "sleep_total_h_p95": 7.17,
    "deep_h_30d_avg": 1.47,
    "deep_h_p5": 0.76,
    "deep_h_p95": 1.94
  },
  "gaps": [
    "No Whoop data for 2026-04-20",
    "No health log for 2026-04-20",
    "No health log for 2026-04-21",
    "No health log for 2026-04-22",
    "No health log for 2026-04-23",
    "No health log for 2026-04-24"
  ],
  "days_since_blood": 120,
  "days_since_thyroid": 61,
  "previous_week_summary": null
};

window.WEEK_DATA = Object.assign({}, PARTIAL_DATA, {
  verdict: "Sleep is the bottleneck this week — 5.71h average against 13.7h cumulative debt, layered on a thyroid that's still underdosed (TSH 6.654, last checked 61 days ago) and four padel sessions on a 1.13 strain:recovery ratio. Saturday's 24% recovery wasn't a bad night; it was the autonomic price of stacking training on inadequate repair. Cap padel at 2 sessions next week, protect 7+ hours in bed nightly until the debt closes, and book the thyroid retest now.",
  bodySignals: [
    {
      title: "Autonomic / Recovery",
      body: "HRV averaged 40.18 ms (-1% vs the 30-day baseline of 40.58) and RHR 65.67 bpm (+0.7) — both technically stable. The averages mask the story: recovery distribution was 1 red, 3 amber, 2 green, with Saturday at 24% after Friday's 87%. HRV CV of 20.5% indicates moderate-high variability — your week-to-week consistency is fragile rather than catastrophic. The Friday-to-Saturday collapse is the classic delayed parasympathetic crash that lands 24–36 hours after cumulative training load, not a same-day signal."
    },
    {
      title: "Sleep Architecture",
      body: "5.71h average sleep against your own 30-day baseline of 5.41h — slightly above your low bar but well below the 7+ hour floor someone with Hashimoto's needs for adequate peripheral T4→T3 conversion. Deep sleep at 1.55h sits right at the 1.5h target (the one structural win). REM at 1.60h is short. Cumulative debt for the week alone was 13.7 hours. With TSH already at 6.654 and anti-TPO at 354.6, sleep restriction directly raises rT3 and blunts deiodinase activity — you are working against your own thyroid medication every night you sleep under six hours."
    },
    {
      title: "Training Load",
      body: "Strain total 60.1, strain:recovery ratio 1.13 — mild functional overreach, not yet a red zone. Four padel sessions in seven days. The recovery sequence (72 → 49 → 47 → 87 → 24 → 41) shows that none of the recovery scores compounded; each padel session was paid for from the next day's autonomic budget. Strength capacity is on your active-concerns list and you're trying to defend lean mass on retatrutide, but high-impact court volume on six-hour nights accelerates muscle loss instead of adaptation. The radial nerve injury in your right tricep also doesn't recover well under chronic sympathetic load."
    },
    {
      title: "Metabolic / Nutrition",
      body: "Protein averaged 64g/day on the 2 days that were actually logged — 53% of your 120g target, with 0 days at target. Retatrutide does the calorie work for you by suppressing appetite, but it does not protect lean mass; that's on you, and at 64g you're not protecting it. Total testosterone (205, Nov '25) compounds the catabolic pressure. Supplement compliance was 2/2 across the board on logged days including both critical thyroid items, but creatine had no entries the entire week. Zero alcohol days, zero late dinners, zero skipped meals reads more like under-logging than perfect adherence — only 2 of 7 days had a health log at all."
    }
  ],
  connections: [
    {
      title: "Sleep debt × thyroid underdosing × recovery crash",
      whoop: "Sleep avg 5.71h, cumulative debt 13.7h, Saturday recovery 24%",
      lab: "TSH 6.654 (Mar '26, 61 days old), anti-TPO 354.6, free T3 2.92 mid-range",
      nutrition: "Protein 64g/day on logged days (53% of target)",
      interpretation: "Sleep deprivation suppresses peripheral T4→T3 conversion by reducing deiodinase-2 activity and raising rT3. With TSH still 6.654 and the NDT dose unreviewed for 61 days, your thyroid medication is being undercut nightly. Insufficient protein removes the substrate for repair before training even begins. Saturday's 24% recovery is the body forcing the rest you didn't book voluntarily.",
      action: "Order a full thyroid panel this week (TSH, fT3, fT4, rT3, anti-TPO) and protect 7h+ in bed every night until sleep debt resolves."
    },
    {
      title: "Padel volume × low protein × retatrutide-driven catabolism",
      whoop: "4 padel sessions, strain:recovery ratio 1.13, recovery never compounded",
      lab: "Total testosterone 205 ng/dL (low, Nov '25), free T 16.8",
      nutrition: "Protein avg 64g vs 120g target, 0 target hits, no creatine logged",
      interpretation: "Retatrutide drives weight loss but does not protect lean mass; protein adequacy and resistance signal are the only counterforces. Low-T physiology already biases catabolism. At 64g protein with 4 high-impact court sessions and a 1.13 strain:recovery ratio, you are losing the lean tissue you can least afford to lose given your active strength-capacity concern and the radial nerve rehab.",
      action: "Lock in 30g protein at every meal — lead with whey/EAAs if reta has killed appetite. Replace at least one padel session next week with structured resistance work and restart logged creatine 5g/day."
    },
    {
      title: "Skin temp + RR elevation × inflammation baseline × gut dysbiosis",
      whoop: "Skin temp 34.29°C (running warm), respiratory rate 15.11 brpm",
      lab: "ESR 22 (high), hs-CRP 1.545, Eosinophils 6.1% (high), Secretory IgA low, Bifidobacterium low, Lactobacillus low, Elastase-1 109 (low)",
      nutrition: "Probiotics 2/2, digestive enzymes 2/2, lactoferrin 2/2, colostrum 2/2 on logged days",
      interpretation: "A mild systemic inflammation signature persists in your January labs (ESR 22, hs-CRP 1.5, eosinophils 6.1%) and a slightly elevated skin temperature with RR 15 is consistent with low-grade immune activation. The May 2025 gut signature — low Bifido/Lacto, low secretory IgA, low pancreatic elastase — is a credible contributor. Hashimoto's autoimmunity lives downstream of gut barrier integrity. Compliance is excellent on logged days but two data points cannot show a trend.",
      action: "Continue the gut protocol exactly as designed and log every day for the next 14 days so we can read the actual trajectory in skin temp, RR and HRV instead of inferring from a 2-day window."
    },
    {
      title: "Logging gap × incomplete picture",
      whoop: "6 of 7 days captured (Monday Apr 20 missing)",
      lab: "n/a",
      nutrition: "Health logs for only 2 of 7 days (Apr 25, Apr 26)",
      interpretation: "The supplement and macro analysis rests on two days. We cannot tell whether the protein deficit is week-wide or skewed by retatrutide-suppressed days, and the zeros across alcohol/late dinners/skipped meals are more likely under-logging than perfect behavior. This is the second highest-leverage fix after sleep — instrumentation precedes action.",
      action: "Log every day this coming week — weight, macros, supplements, alcohol, training. Set a 9 PM phone reminder if needed."
    }
  ],
  actions: [
    {
      priority: 1,
      category: "Medical",
      timeframe: "This week",
      text: "Book a full thyroid panel (TSH, fT3, fT4, rT3, anti-TPO) — 61 days since last, NDT dose review is overdue with TSH still 6.654."
    },
    {
      priority: 2,
      category: "Sleep",
      timeframe: "Tonight",
      text: "7+ hours in bed every night until the 13.7h sleep debt closes — lights out by 10:30 PM, phone out of the bedroom."
    },
    {
      priority: 3,
      category: "Training",
      timeframe: "This week",
      text: "Cap padel at 2 sessions and replace one with structured resistance training to defend lean mass on retatrutide."
    },
    {
      priority: 4,
      category: "Nutrition",
      timeframe: "This week",
      text: "Hit 120g protein every day — 30g per meal, leading with whey or EAAs if retatrutide has suppressed appetite."
    },
    {
      priority: 5,
      category: "Nutrition",
      timeframe: "Tonight",
      text: "Log every day this week (weight, macros, supplements, alcohol). The current 2/7 health logs are blinding the dashboard."
    },
    {
      priority: 6,
      category: "Supplements",
      timeframe: "This week",
      text: "Restart and log creatine 5g daily — no entries the entire week, and it is load-bearing for the strength work."
    },
    {
      priority: 7,
      category: "Medical",
      timeframe: "Within 2 weeks",
      text: "Add a full follow-up panel (lipids + ApoB, fasting insulin, HbA1c, hs-CRP, ESR, ferritin) — 120 days since the last comprehensive draw."
    }
  ]
});
