// Auto-generated by weekly-health-briefing/starter.py
// Deterministic fields. Verdict, bodySignals, connections, actions are appended at runtime.
const PARTIAL_DATA = {
  "patient": {
    "name": "Pratik",
    "age": 42,
    "week": "Week 17 \u00b7 2026",
    "dateRange": "Apr 20 \u2014 Apr 26, 2026"
  },
  "days": [
    {
      "day": "Mon",
      "date": "Apr 20",
      "recovery": {
        "score": 0,
        "hrv": 0,
        "rhr": 0,
        "spo2": 0,
        "skinTemp": 0
      },
      "sleep": {
        "total": 0,
        "deep": 0,
        "rem": 0,
        "light": 0,
        "eff": 0,
        "perf": 0,
        "cons": 0,
        "rr": 0,
        "dist": 0,
        "needed": 0,
        "debt": 0
      },
      "strain": {
        "score": 0,
        "kj": 0,
        "avg": 0,
        "max": 0
      },
      "workout": null,
      "food": {
        "dinner": "\u2014",
        "late": false,
        "alcohol": 0,
        "skipped": null,
        "lastMeal": "\u2014"
      },
      "supps": {
        "taken": 0,
        "missed": [],
        "total": 0
      },
      "is_gap": true
    },
    {
      "day": "Tue",
      "date": "Apr 21",
      "recovery": {
        "score": 72,
        "hrv": 50.114056,
        "rhr": 63,
        "spo2": 91.833336,
        "skinTemp": 34.199
      },
      "sleep": {
        "total": 5.34,
        "deep": 1.68,
        "rem": 1.58,
        "light": 2.08,
        "eff": 91.04171,
        "perf": 68,
        "cons": 64,
        "rr": 15.410156,
        "dist": 10,
        "needed": 9.36,
        "debt": 1.81
      },
      "strain": {
        "score": 15.935356,
        "kj": 12504.708,
        "avg": 77,
        "max": 170
      },
      "workout": {
        "sport": "Workout",
        "min": 0,
        "strain": 15.448894,
        "avg": 141,
        "max": 170,
        "kj": 3926.9348
      },
      "food": {
        "dinner": "\u2014",
        "late": false,
        "alcohol": 0,
        "skipped": null,
        "lastMeal": "\u2014"
      },
      "supps": {
        "taken": 0,
        "missed": [],
        "total": 0
      },
      "is_gap": false
    },
    {
      "day": "Wed",
      "date": "Apr 22",
      "recovery": {
        "score": 49,
        "hrv": 36.74493,
        "rhr": 66,
        "spo2": 95.954544,
        "skinTemp": 34.156
      },
      "sleep": {
        "total": 6.0,
        "deep": 1.8,
        "rem": 1.93,
        "light": 2.27,
        "eff": 85.705826,
        "perf": 69,
        "cons": 76,
        "rr": 15.410156,
        "dist": 12,
        "needed": 10.35,
        "debt": 2.13
      },
      "strain": {
        "score": 12.494325,
        "kj": 9408.404,
        "avg": 76,
        "max": 150
      },
      "workout": {
        "sport": "Meditation",
        "min": 53,
        "strain": 11.751642,
        "avg": 109,
        "max": 150,
        "kj": 802.5154
      },
      "food": {
        "dinner": "\u2014",
        "late": false,
        "alcohol": 0,
        "skipped": null,
        "lastMeal": "\u2014"
      },
      "supps": {
        "taken": 0,
        "missed": [],
        "total": 0
      },
      "is_gap": false
    },
    {
      "day": "Thu",
      "date": "Apr 23",
      "recovery": {
        "score": 47,
        "hrv": 35.19561,
        "rhr": 67,
        "spo2": 97.2,
        "skinTemp": 34.724167
      },
      "sleep": {
        "total": 5.93,
        "deep": 1.46,
        "rem": 1.24,
        "light": 3.23,
        "eff": 95.68604,
        "perf": 75,
        "cons": 84,
        "rr": 15.395508,
        "dist": 10,
        "needed": 9.99,
        "debt": 2.13
      },
      "strain": {
        "score": 4.3089447,
        "kj": 8475.419,
        "avg": 70,
        "max": 124
      },
      "workout": null,
      "food": {
        "dinner": "\u2014",
        "late": false,
        "alcohol": 0,
        "skipped": null,
        "lastMeal": "\u2014"
      },
      "supps": {
        "taken": 0,
        "missed": [],
        "total": 0
      },
      "is_gap": false
    },
    {
      "day": "Fri",
      "date": "Apr 24",
      "recovery": {
        "score": 87,
        "hrv": 50.886986,
        "rhr": 64,
        "spo2": 96.1,
        "skinTemp": 34.11779
      },
      "sleep": {
        "total": 7.25,
        "deep": 1.58,
        "rem": 2.28,
        "light": 3.39,
        "eff": 94.56865,
        "perf": 84,
        "cons": 81,
        "rr": 14.765625,
        "dist": 22,
        "needed": 9.67,
        "debt": 2.13
      },
      "strain": {
        "score": 17.14685,
        "kj": 13805.713,
        "avg": 81,
        "max": 179
      },
      "workout": {
        "sport": "Workout",
        "min": 0,
        "strain": 15.565295,
        "avg": 144,
        "max": 179,
        "kj": 3800.8044
      },
      "food": {
        "dinner": "\u2014",
        "late": false,
        "alcohol": 0,
        "skipped": null,
        "lastMeal": "\u2014"
      },
      "supps": {
        "taken": 0,
        "missed": [],
        "total": 0
      },
      "is_gap": false
    },
    {
      "day": "Sat",
      "date": "Apr 25",
      "recovery": {
        "score": 24,
        "hrv": 36.8135,
        "rhr": 66,
        "spo2": 96,
        "skinTemp": 34.215668
      },
      "sleep": {
        "total": 3.63,
        "deep": 1.31,
        "rem": 0.92,
        "light": 1.4,
        "eff": 98.639885,
        "perf": 40,
        "cons": 76,
        "rr": 14.765625,
        "dist": 4,
        "needed": 9.91,
        "debt": 1.55
      },
      "strain": {
        "score": 4.255712,
        "kj": 8189.8267,
        "avg": 72,
        "max": 130
      },
      "workout": null,
      "food": {
        "dinner": "Salad, 1 sandwich with coleslaw",
        "late": false,
        "alcohol": 0,
        "skipped": null,
        "lastMeal": "\u2014"
      },
      "supps": {
        "taken": 20,
        "missed": [],
        "total": 20
      },
      "is_gap": false
    },
    {
      "day": "Sun",
      "date": "Apr 26",
      "recovery": {
        "score": 41,
        "hrv": 31.342546,
        "rhr": 68,
        "spo2": 97.4,
        "skinTemp": 34.349335
      },
      "sleep": {
        "total": 6.12,
        "deep": 1.48,
        "rem": 1.68,
        "light": 2.96,
        "eff": 90.17126,
        "perf": 75,
        "cons": 69,
        "rr": 14.941406,
        "dist": 16,
        "needed": 9.67,
        "debt": 2.13
      },
      "strain": {
        "score": 5.965974,
        "kj": 8612.794,
        "avg": 74,
        "max": 165
      },
      "workout": null,
      "food": {
        "dinner": "Rice and Asian curry, veg sushi",
        "late": false,
        "alcohol": 2,
        "skipped": null,
        "lastMeal": "\u2014",
        "note": "2 sake shots"
      },
      "supps": {
        "taken": 20,
        "missed": [],
        "total": 20
      },
      "is_gap": false
    }
  ],
  "derived": {
    "hrvAvg7d": 40.18,
    "hrvAvg30d": 40.58,
    "hrvCv": 20.5,
    "hrvTrend": "stable",
    "hrv4wkTrend": [
      40.18,
      40.18,
      40.18,
      40.18,
      40.18
    ],
    "rhrAvg7d": 65.67,
    "rhrAvg30d": 64.95,
    "rhrTrend": "stable",
    "rhr4wkTrend": [
      65.67,
      65.67,
      65.67,
      65.67,
      65.67
    ],
    "recoveryAvg7d": 53,
    "recoveryAvg30d": 47,
    "recoveryBand": [
      16,
      85
    ],
    "deepAvg7d": 1.55,
    "deepTarget": 1.5,
    "sleepDebtCum": 13.7,
    "sleepBand": [
      3.54,
      7.17
    ],
    "deepBand": [
      0.76,
      1.94
    ],
    "hrvBand": [
      22.36,
      51.72
    ],
    "rhrBand": [
      61,
      77
    ],
    "strainRecRatio": 1.13,
    "totalStrain": 60.1,
    "padelSessions": 4,
    "daysSinceBlood": 120,
    "daysSinceThyroid": 61,
    "proteinAvg30d": 0,
    "proteinTarget": 120,
    "caloriesAvg30d": 0,
    "carbsAvg30d": 0,
    "fatAvg30d": 0,
    "lateDinners30d": 0.0,
    "alcoholDays30d": 0.0,
    "suppsAvg30d": 0,
    "suppsTotalsByCategory": {
      "critical": {
        "taken": 4,
        "total": 4
      },
      "adjunct": {
        "taken": 36,
        "total": 36
      },
      "overall": {
        "taken": 40,
        "total": 40
      }
    }
  },
  "nutrition": [
    {
      "day": "Mon",
      "date": "Apr 20",
      "cal": 0,
      "protein": 0,
      "carbs": 0,
      "fat": 0,
      "lastMeal": "\u2014",
      "late": false,
      "alcohol": 0,
      "flags": []
    },
    {
      "day": "Tue",
      "date": "Apr 21",
      "cal": 0,
      "protein": 0,
      "carbs": 0,
      "fat": 0,
      "lastMeal": "\u2014",
      "late": false,
      "alcohol": 0,
      "flags": []
    },
    {
      "day": "Wed",
      "date": "Apr 22",
      "cal": 0,
      "protein": 0,
      "carbs": 0,
      "fat": 0,
      "lastMeal": "\u2014",
      "late": false,
      "alcohol": 0,
      "flags": []
    },
    {
      "day": "Thu",
      "date": "Apr 23",
      "cal": 0,
      "protein": 0,
      "carbs": 0,
      "fat": 0,
      "lastMeal": "\u2014",
      "late": false,
      "alcohol": 0,
      "flags": []
    },
    {
      "day": "Fri",
      "date": "Apr 24",
      "cal": 0,
      "protein": 0,
      "carbs": 0,
      "fat": 0,
      "lastMeal": "\u2014",
      "late": false,
      "alcohol": 0,
      "flags": []
    },
    {
      "day": "Sat",
      "date": "Apr 25",
      "cal": 1135,
      "protein": 90,
      "carbs": 68,
      "fat": 58,
      "lastMeal": "\u2014",
      "late": false,
      "alcohol": 0,
      "flags": []
    },
    {
      "day": "Sun",
      "date": "Apr 26",
      "cal": 1080,
      "protein": 38,
      "carbs": 182,
      "fat": 22,
      "lastMeal": "\u2014",
      "late": false,
      "alcohol": 2,
      "flags": [
        "alcohol"
      ]
    }
  ],
  "bloods": [
    {
      "marker": "TSH",
      "value": 6.654,
      "unit": "\u00b5IU/mL",
      "range": "0.4\u20134.78",
      "status": "high",
      "sev": "amber"
    },
    {
      "marker": "FT3",
      "value": 2.92,
      "unit": "pg/mL",
      "range": "2.0\u20134.4",
      "status": "in_range",
      "sev": "green"
    },
    {
      "marker": "FT4",
      "value": 1.11,
      "unit": "ng/dL",
      "range": "0.89\u20131.76",
      "status": "in_range",
      "sev": "green"
    },
    {
      "marker": "Testosterone",
      "value": 205.0,
      "unit": "ng/dL",
      "range": "249\u2013836",
      "status": "low",
      "sev": "red"
    },
    {
      "marker": "Fasting Insulin",
      "value": 13.0,
      "unit": "\u00b5IU/mL",
      "range": "2\u201325",
      "status": "in_range",
      "sev": "green"
    },
    {
      "marker": "HbA1c",
      "value": 5.6,
      "unit": "%",
      "range": "<5.7",
      "status": "in_range",
      "sev": "green"
    },
    {
      "marker": "Glucose (FS)",
      "value": 99.0,
      "unit": "mg/dL",
      "range": "70\u2013100",
      "status": "in_range",
      "sev": "green"
    },
    {
      "marker": "LDL",
      "value": 156.6,
      "unit": "mg/dL",
      "range": "<100",
      "status": "high",
      "sev": "red"
    },
    {
      "marker": "HDL",
      "value": 41.0,
      "unit": "mg/dL",
      "range": ">40",
      "status": "in_range",
      "sev": "green"
    },
    {
      "marker": "ApoB",
      "value": 132.0,
      "unit": "mg/dL",
      "range": "56\u2013145",
      "status": "in_range",
      "sev": "green"
    },
    {
      "marker": "Homocysteine",
      "value": 8.48,
      "unit": "\u00b5mol/L",
      "range": "<15",
      "status": "in_range",
      "sev": "green"
    },
    {
      "marker": "ESR",
      "value": 22.0,
      "unit": "mm/hr",
      "range": "0\u201315",
      "status": "high",
      "sev": "amber"
    }
  ],
  "conditions": [
    "Hashimoto's Thyroiditis (autoimmune hypothyroidism)",
    "Low Testosterone (Hypogonadism)",
    "Grade I Fatty Liver",
    "MTHFR A1298C Homozygous Mutation",
    "Borderline Insulin Resistance",
    "Radial Nerve Injury (Right Tricep)"
  ],
  "medications": [
    {
      "name": "Thyroid (compounded NDT \u2014 Bella Sante)",
      "dose": "T3 20mcg + T4 40mcg (1 pill)",
      "freq": "twice daily"
    },
    {
      "name": "Retatrutide (GLP-1/GIP/glucagon triple agonist)",
      "dose": "2000mcg weekly, Saturday morning",
      "freq": "weekly"
    }
  ],
  "supplements": [
    {
      "name": "T3+T4 thyroid medication",
      "taken": 2,
      "total": 2,
      "critical": true
    },
    {
      "name": "Liposomal Glutathione",
      "taken": 2,
      "total": 2,
      "critical": false
    },
    {
      "name": "Creatine",
      "taken": 0,
      "total": 0,
      "critical": false
    },
    {
      "name": "Magnesium + salt water",
      "taken": 2,
      "total": 2,
      "critical": false
    },
    {
      "name": "Digestive enzymes",
      "taken": 2,
      "total": 2,
      "critical": false
    },
    {
      "name": "Vit D3+K2",
      "taken": 2,
      "total": 2,
      "critical": false
    },
    {
      "name": "B complex",
      "taken": 2,
      "total": 2,
      "critical": false
    },
    {
      "name": "Omega 3",
      "taken": 2,
      "total": 2,
      "critical": false
    },
    {
      "name": "Shilajit",
      "taken": 2,
      "total": 2,
      "critical": false
    },
    {
      "name": "DHEAs",
      "taken": 2,
      "total": 2,
      "critical": false
    },
    {
      "name": "Myo inositol + Collagen + EAA Thorne",
      "taken": 2,
      "total": 2,
      "critical": false
    },
    {
      "name": "Colostrum",
      "taken": 2,
      "total": 2,
      "critical": false
    },
    {
      "name": "Lactoferrin",
      "taken": 2,
      "total": 2,
      "critical": false
    },
    {
      "name": "Nato Serra",
      "taken": 2,
      "total": 2,
      "critical": false
    },
    {
      "name": "T3 thyroid medication",
      "taken": 2,
      "total": 2,
      "critical": true
    },
    {
      "name": "TMG",
      "taken": 2,
      "total": 2,
      "critical": false
    },
    {
      "name": "Zinc",
      "taken": 2,
      "total": 2,
      "critical": false
    },
    {
      "name": "Probiotics",
      "taken": 2,
      "total": 2,
      "critical": false
    },
    {
      "name": "Magnesium Bisglycinate",
      "taken": 2,
      "total": 2,
      "critical": false
    },
    {
      "name": "Black seed oil",
      "taken": 2,
      "total": 2,
      "critical": false
    },
    {
      "name": "Detox Binder",
      "taken": 2,
      "total": 2,
      "critical": false
    }
  ],
  "window": "Apr 20 \u2014 Apr 26, 2026",
  "window_start": "2026-04-20",
  "window_end": "2026-04-26",
  "generated_at": "2026-05-01T10:45:45.071990",
  "weekly_metrics": {
    "hrv_avg": 40.18,
    "hrv_cv": 20.5,
    "hrv_vs_30d_pct": -1.0,
    "hrv_trend": "stable",
    "rhr_avg": 65.67,
    "rhr_vs_30d": 0.7,
    "rhr_trend": "stable",
    "recovery_avg": 53.33,
    "recovery_distribution": {
      "red": 1,
      "amber": 3,
      "green": 2
    },
    "sleep_avg_h": 5.71,
    "deep_avg_h": 1.55,
    "deep_target_h": 1.5,
    "rem_avg_h": 1.6,
    "light_avg_h": 2.56,
    "efficiency_avg": 92.64,
    "sleep_debt_cum_h": 13.7,
    "strain_total": 60.1,
    "strain_recovery_ratio": 1.13,
    "padel_sessions": 4,
    "skin_temp_avg": 34.29,
    "rr_avg": 15.11,
    "supp_compliance": {
      "T3+T4 thyroid medication": "2/2 [critical-med]",
      "Liposomal Glutathione": "2/2",
      "Creatine": "no logs",
      "Magnesium + salt water": "2/2",
      "Digestive enzymes": "2/2",
      "Vit D3+K2": "2/2",
      "B complex": "2/2",
      "Omega 3": "2/2",
      "Shilajit": "2/2",
      "DHEAs": "2/2",
      "Myo inositol + Collagen + EAA Thorne": "2/2",
      "Colostrum": "2/2",
      "Lactoferrin": "2/2",
      "Nato Serra": "2/2",
      "T3 thyroid medication": "2/2 [critical-med]",
      "TMG": "2/2",
      "Zinc": "2/2",
      "Probiotics": "2/2",
      "Magnesium Bisglycinate": "2/2",
      "Black seed oil": "2/2",
      "Detox Binder": "2/2"
    },
    "protein_avg_g": 64,
    "protein_target_hits": 0,
    "alcohol_days": 1,
    "late_dinners": 0,
    "skipped_meals": 0
  },
  "day_summaries": [
    {
      "day": "Mon",
      "date": "2026-04-20",
      "recovery": null,
      "key_event": "\u2014"
    },
    {
      "day": "Tue",
      "date": "2026-04-21",
      "recovery": 72,
      "key_event": "Workout"
    },
    {
      "day": "Wed",
      "date": "2026-04-22",
      "recovery": 49,
      "key_event": "Workout"
    },
    {
      "day": "Thu",
      "date": "2026-04-23",
      "recovery": 47,
      "key_event": "\u2014"
    },
    {
      "day": "Fri",
      "date": "2026-04-24",
      "recovery": 87,
      "key_event": "Workout"
    },
    {
      "day": "Sat",
      "date": "2026-04-25",
      "recovery": 24,
      "key_event": "\u2014"
    },
    {
      "day": "Sun",
      "date": "2026-04-26",
      "recovery": 41,
      "key_event": "alcohol"
    }
  ],
  "daily_macros": {
    "2026-04-20": {
      "cal": null,
      "protein": null,
      "carb": null,
      "fat": null
    },
    "2026-04-21": {
      "cal": null,
      "protein": null,
      "carb": null,
      "fat": null
    },
    "2026-04-22": {
      "cal": null,
      "protein": null,
      "carb": null,
      "fat": null
    },
    "2026-04-23": {
      "cal": null,
      "protein": null,
      "carb": null,
      "fat": null
    },
    "2026-04-24": {
      "cal": null,
      "protein": null,
      "carb": null,
      "fat": null
    },
    "2026-04-25": {
      "cal": 1135,
      "protein": 90,
      "carb": 68,
      "fat": 58
    },
    "2026-04-26": {
      "cal": 1080,
      "protein": 38,
      "carb": 182,
      "fat": 22
    }
  },
  "blood_baselines": {
    "TSH": {
      "value": 6.654,
      "date": "Mar '26",
      "date_iso": "2026-03-01",
      "status": "high",
      "unit": "\u00b5IU/mL",
      "range_text": "0.4\u20134.78"
    },
    "Free T3": {
      "value": 2.92,
      "date": "Mar '26",
      "date_iso": "2026-03-01",
      "status": "in_range",
      "unit": "pg/mL",
      "range_text": "2.0\u20134.4"
    },
    "Free T4": {
      "value": 1.11,
      "date": "Mar '26",
      "date_iso": "2026-03-01",
      "status": "in_range",
      "unit": "ng/dL",
      "range_text": "0.89\u20131.76"
    },
    "Total T3": {
      "value": 134.0,
      "date": "May '25",
      "date_iso": "2025-05-01",
      "status": "in_range",
      "unit": "ng/dL",
      "range_text": "60\u2013181"
    },
    "Total T4": {
      "value": 7.92,
      "date": "May '25",
      "date_iso": "2025-05-01",
      "status": "in_range",
      "unit": "\u00b5g/dL",
      "range_text": "4.5\u201312.0"
    },
    "Anti-TPO": {
      "value": 354.6,
      "date": "Mar '26",
      "date_iso": "2026-03-01",
      "status": "high",
      "unit": "IU/mL",
      "range_text": "<60"
    },
    "Anti-TG": {
      "value": 13.6,
      "date": "Mar '26",
      "date_iso": "2026-03-01",
      "status": "high",
      "unit": "IU/mL",
      "range_text": "<4.5"
    },
    "TSH Receptor Ab": {
      "value": 3.11,
      "date": "May '25",
      "date_iso": "2025-05-01",
      "status": "high",
      "unit": "IU/L",
      "range_text": "<1.75"
    },
    "Total Testosterone": {
      "value": 205.0,
      "date": "Nov '25",
      "date_iso": "2025-11-01",
      "status": "low",
      "unit": "ng/dL",
      "range_text": "249\u2013836"
    },
    "Free Testosterone": {
      "value": 16.8,
      "date": "Nov '25",
      "date_iso": "2025-11-01",
      "status": "in_range",
      "unit": "pg/mL",
      "range_text": "15\u201350"
    },
    "DHEAS": {
      "value": 293.0,
      "date": "Nov '25",
      "date_iso": "2025-11-01",
      "status": "in_range",
      "unit": "\u00b5g/dL",
      "range_text": "88.9\u2013427"
    },
    "PSA (Total)": {
      "value": 0.619,
      "date": "Apr '22",
      "date_iso": "2022-04-01",
      "status": null,
      "unit": "ng/mL",
      "range_text": "\u22642.0"
    },
    "Glucose Fasting": {
      "value": 99.0,
      "date": "Jan '26",
      "date_iso": "2026-01-01",
      "status": "in_range",
      "unit": "mg/dL",
      "range_text": "70\u2013100"
    },
    "Glucose PP": {
      "value": 103.0,
      "date": "Jan '26",
      "date_iso": "2026-01-01",
      "status": "in_range",
      "unit": "mg/dL",
      "range_text": "<140"
    },
    "HbA1c": {
      "value": 5.6,
      "date": "Jan '26",
      "date_iso": "2026-01-01",
      "status": "in_range",
      "unit": "%",
      "range_text": "<5.7"
    },
    "Insulin Fasting": {
      "value": 13.0,
      "date": "Jan '26",
      "date_iso": "2026-01-01",
      "status": "in_range",
      "unit": "\u00b5IU/mL",
      "range_text": "2\u201325"
    },
    "Insulin PP": {
      "value": 45.1,
      "date": "Jan '26",
      "date_iso": "2026-01-01",
      "status": "in_range",
      "unit": "\u00b5IU/mL",
      "range_text": "<140"
    },
    "C-Peptide": {
      "value": 2.94,
      "date": "Jan '26",
      "date_iso": "2026-01-01",
      "status": null,
      "unit": "ng/mL",
      "range_text": ""
    },
    "Fructosamine": {
      "value": 251.3,
      "date": "May '25",
      "date_iso": "2025-05-01",
      "status": null,
      "unit": "\u00b5mol/L",
      "range_text": ""
    },
    "Homocysteine": {
      "value": 8.48,
      "date": "Jan '26",
      "date_iso": "2026-01-01",
      "status": "in_range",
      "unit": "\u00b5mol/L",
      "range_text": "<15"
    },
    "Total Cholesterol": {
      "value": 223.0,
      "date": "Jan '26",
      "date_iso": "2026-01-01",
      "status": "high",
      "unit": "mg/dL",
      "range_text": "<200"
    },
    "LDL Cholesterol": {
      "value": 156.6,
      "date": "Jan '26",
      "date_iso": "2026-01-01",
      "status": "high",
      "unit": "mg/dL",
      "range_text": "<100"
    },
    "HDL Cholesterol": {
      "value": 41.0,
      "date": "Jan '26",
      "date_iso": "2026-01-01",
      "status": "in_range",
      "unit": "mg/dL",
      "range_text": ">40"
    },
    "Triglycerides": {
      "value": 127.0,
      "date": "Jan '26",
      "date_iso": "2026-01-01",
      "status": null,
      "unit": "mg/dL",
      "range_text": ""
    },
    "VLDL": {
      "value": 25.4,
      "date": "Jan '26",
      "date_iso": "2026-01-01",
      "status": null,
      "unit": "mg/dL",
      "range_text": ""
    },
    "Non-HDL Cholesterol": {
      "value": 182.0,
      "date": "Jan '26",
      "date_iso": "2026-01-01",
      "status": null,
      "unit": "mg/dL",
      "range_text": ""
    },
    "TC/HDL Ratio": {
      "value": 5.4,
      "date": "Jan '26",
      "date_iso": "2026-01-01",
      "status": null,
      "unit": "\u2014",
      "range_text": ""
    },
    "LDL/HDL Ratio": {
      "value": 3.8,
      "date": "Jan '26",
      "date_iso": "2026-01-01",
      "status": null,
      "unit": "\u2014",
      "range_text": ""
    },
    "Lp(a)": {
      "value": 14.6,
      "date": "Nov '25",
      "date_iso": "2025-11-01",
      "status": "in_range",
      "unit": "mg/dL",
      "range_text": "<30"
    },
    "LP-PLA2": {
      "value": 128.0,
      "date": "May '25",
      "date_iso": "2025-05-01",
      "status": null,
      "unit": "nmol/min/mL",
      "range_text": ""
    },
    "ApoA1": {
      "value": 147.0,
      "date": "Nov '25",
      "date_iso": "2025-11-01",
      "status": null,
      "unit": "mg/dL",
      "range_text": ""
    },
    "ApoB": {
      "value": 132.0,
      "date": "Nov '25",
      "date_iso": "2025-11-01",
      "status": "in_range",
      "unit": "mg/dL",
      "range_text": "56\u2013145"
    },
    "ALT (SGPT)": {
      "value": 39.0,
      "date": "Jan '26",
      "date_iso": "2026-01-01",
      "status": "in_range",
      "unit": "U/L",
      "range_text": "<41"
    },
    "AST (SGOT)": {
      "value": 26.0,
      "date": "Jan '26",
      "date_iso": "2026-01-01",
      "status": "in_range",
      "unit": "U/L",
      "range_text": "<40"
    },
    "ALP": {
      "value": 86.0,
      "date": "Jan '26",
      "date_iso": "2026-01-01",
      "status": "in_range",
      "unit": "U/L",
      "range_text": "40\u2013129"
    },
    "GGT": {
      "value": 42.0,
      "date": "Jan '26",
      "date_iso": "2026-01-01",
      "status": "in_range",
      "unit": "U/L",
      "range_text": "<73"
    },
    "Bilirubin Total": {
      "value": 0.94,
      "date": "Jan '26",
      "date_iso": "2026-01-01",
      "status": "in_range",
      "unit": "mg/dL",
      "range_text": "0\u20131.2"
    },
    "Bilirubin Direct": {
      "value": 0.35,
      "date": "Jan '26",
      "date_iso": "2026-01-01",
      "status": "high",
      "unit": "mg/dL",
      "range_text": "0\u20130.3"
    },
    "Bilirubin Indirect": {
      "value": 0.59,
      "date": "Jan '26",
      "date_iso": "2026-01-01",
      "status": "in_range",
      "unit": "mg/dL",
      "range_text": "0\u20131.0"
    },
    "LDH": {
      "value": 165.0,
      "date": "Jan '26",
      "date_iso": "2026-01-01",
      "status": "in_range",
      "unit": "U/L",
      "range_text": "120\u2013250"
    },
    "Total Protein": {
      "value": 7.7,
      "date": "Jan '26",
      "date_iso": "2026-01-01",
      "status": "in_range",
      "unit": "gm/dL",
      "range_text": "5.7\u20138.2"
    },
    "Albumin": {
      "value": 4.5,
      "date": "Jan '26",
      "date_iso": "2026-01-01",
      "status": "in_range",
      "unit": "gm/dL",
      "range_text": "3.2\u20135.2"
    },
    "Globulin": {
      "value": 3.2,
      "date": "Jan '26",
      "date_iso": "2026-01-01",
      "status": "in_range",
      "unit": "gm/dL",
      "range_text": "2.3\u20133.6"
    },
    "A/G Ratio": {
      "value": 1.4,
      "date": "Jan '26",
      "date_iso": "2026-01-01",
      "status": "in_range",
      "unit": "\u2014",
      "range_text": "1.1\u20132.2"
    },
    "Creatinine": {
      "value": 0.77,
      "date": "Jan '26",
      "date_iso": "2026-01-01",
      "status": "in_range",
      "unit": "mg/dL",
      "range_text": "0.67\u20131.2"
    },
    "BUN": {
      "value": 16.8,
      "date": "Jan '26",
      "date_iso": "2026-01-01",
      "status": "in_range",
      "unit": "mg/dL",
      "range_text": "6\u201320"
    },
    "Urea": {
      "value": 36.0,
      "date": "Jan '26",
      "date_iso": "2026-01-01",
      "status": "in_range",
      "unit": "mg/dL",
      "range_text": "15\u201348"
    },
    "Uric Acid": {
      "value": 5.6,
      "date": "Jan '26",
      "date_iso": "2026-01-01",
      "status": "in_range",
      "unit": "mg/dL",
      "range_text": "3.4\u20137.0"
    },
    "eGFR": {
      "value": 114.0,
      "date": "Jan '26",
      "date_iso": "2026-01-01",
      "status": "in_range",
      "unit": "mL/min/1.73m\u00b2",
      "range_text": ">90"
    },
    "Cystatin C": {
      "value": 0.81,
      "date": "May '25",
      "date_iso": "2025-05-01",
      "status": null,
      "unit": "mg/L",
      "range_text": "\u22641.03"
    },
    "Hemoglobin": {
      "value": 15.4,
      "date": "Jan '26",
      "date_iso": "2026-01-01",
      "status": "in_range",
      "unit": "g/dL",
      "range_text": "13\u201317.5"
    },
    "RBC": {
      "value": 5.04,
      "date": "Jan '26",
      "date_iso": "2026-01-01",
      "status": "in_range",
      "unit": "mill/\u00b5L",
      "range_text": "4.4\u20136.0"
    },
    "Hematocrit (PCV)": {
      "value": 46.4,
      "date": "Jan '26",
      "date_iso": "2026-01-01",
      "status": "in_range",
      "unit": "%",
      "range_text": "40\u201352"
    },
    "MCV": {
      "value": 92.0,
      "date": "Jan '26",
      "date_iso": "2026-01-01",
      "status": "in_range",
      "unit": "fL",
      "range_text": "82\u2013101"
    },
    "MCH": {
      "value": 30.5,
      "date": "Jan '26",
      "date_iso": "2026-01-01",
      "status": "in_range",
      "unit": "pg",
      "range_text": "27\u201334"
    },
    "MCHC": {
      "value": 33.2,
      "date": "Jan '26",
      "date_iso": "2026-01-01",
      "status": "in_range",
      "unit": "g/dL",
      "range_text": "31.5\u201336"
    },
    "RDW": {
      "value": 12.7,
      "date": "Jan '26",
      "date_iso": "2026-01-01",
      "status": "in_range",
      "unit": "%",
      "range_text": "11.5\u201314"
    },
    "WBC": {
      "value": 6.58,
      "date": "Jan '26",
      "date_iso": "2026-01-01",
      "status": "in_range",
      "unit": "x10\u00b3/\u00b5L",
      "range_text": "4\u201310.3"
    },
    "Neutrophils %": {
      "value": 50.5,
      "date": "Jan '26",
      "date_iso": "2026-01-01",
      "status": "in_range",
      "unit": "%",
      "range_text": "40\u201380"
    },
    "Lymphocytes %": {
      "value": 36.8,
      "date": "Jan '26",
      "date_iso": "2026-01-01",
      "status": "in_range",
      "unit": "%",
      "range_text": "20\u201340"
    },
    "Monocytes %": {
      "value": 6.5,
      "date": "Jan '26",
      "date_iso": "2026-01-01",
      "status": "in_range",
      "unit": "%",
      "range_text": "2\u201310"
    },
    "Eosinophils %": {
      "value": 6.1,
      "date": "Jan '26",
      "date_iso": "2026-01-01",
      "status": "high",
      "unit": "%",
      "range_text": "0\u20136"
    },
    "Basophils %": {
      "value": 0.1,
      "date": "Jan '26",
      "date_iso": "2026-01-01",
      "status": "in_range",
      "unit": "%",
      "range_text": "0\u20132"
    },
    "Platelet Count": {
      "value": 306.0,
      "date": "Jan '26",
      "date_iso": "2026-01-01",
      "status": "in_range",
      "unit": "x10\u00b3/\u00b5L",
      "range_text": "150\u2013440"
    },
    "MPV": {
      "value": 11.1,
      "date": "Jan '26",
      "date_iso": "2026-01-01",
      "status": "high",
      "unit": "fL",
      "range_text": "7.5\u201311"
    },
    "ESR": {
      "value": 22.0,
      "date": "Jan '26",
      "date_iso": "2026-01-01",
      "status": "high",
      "unit": "mm/hr",
      "range_text": "0\u201315"
    },
    "Serum Iron": {
      "value": 119.0,
      "date": "Jan '26",
      "date_iso": "2026-01-01",
      "status": "in_range",
      "unit": "\u00b5g/dL",
      "range_text": "65\u2013175"
    },
    "TIBC": {
      "value": 329.0,
      "date": "Jan '26",
      "date_iso": "2026-01-01",
      "status": "in_range",
      "unit": "\u00b5g/dL",
      "range_text": "250\u2013450"
    },
    "Transferrin Saturation": {
      "value": 36.0,
      "date": "Jan '26",
      "date_iso": "2026-01-01",
      "status": "in_range",
      "unit": "%",
      "range_text": "12\u201345"
    },
    "Ferritin": {
      "value": 51.3,
      "date": "Jan '26",
      "date_iso": "2026-01-01",
      "status": "in_range",
      "unit": "ng/mL",
      "range_text": "22\u2013400"
    },
    "UIBC": {
      "value": 210.0,
      "date": "Jan '26",
      "date_iso": "2026-01-01",
      "status": "in_range",
      "unit": "\u00b5g/dL",
      "range_text": "125\u2013345"
    },
    "Vitamin D (25-OH)": {
      "value": 46.6,
      "date": "Jan '26",
      "date_iso": "2026-01-01",
      "status": "in_range",
      "unit": "ng/mL",
      "range_text": "30\u2013100"
    },
    "Vitamin B12": {
      "value": 411.0,
      "date": "Jan '26",
      "date_iso": "2026-01-01",
      "status": "in_range",
      "unit": "pg/mL",
      "range_text": "197\u2013771"
    },
    "Vitamin A": {
      "value": 668.38,
      "date": "May '25",
      "date_iso": "2025-05-01",
      "status": "in_range",
      "unit": "ng/mL",
      "range_text": "300\u2013800"
    },
    "Vitamin E": {
      "value": 10844.0,
      "date": "May '25",
      "date_iso": "2025-05-01",
      "status": "in_range",
      "unit": "ng/mL",
      "range_text": "5500\u201318000"
    },
    "Vitamin K": {
      "value": 0.17,
      "date": "May '25",
      "date_iso": "2025-05-01",
      "status": "in_range",
      "unit": "ng/mL",
      "range_text": "0.13\u20131.19"
    },
    "Vitamin B1 (Thiamin)": {
      "value": 0.78,
      "date": "May '25",
      "date_iso": "2025-05-01",
      "status": "in_range",
      "unit": "ng/mL",
      "range_text": "0.5\u20134.0"
    },
    "Vitamin B2 (Riboflavin)": {
      "value": 9.77,
      "date": "May '25",
      "date_iso": "2025-05-01",
      "status": "in_range",
      "unit": "ng/mL",
      "range_text": "1.6\u201368.2"
    },
    "Vitamin B3 (Nicotinic)": {
      "value": 1.38,
      "date": "May '25",
      "date_iso": "2025-05-01",
      "status": "in_range",
      "unit": "ng/mL",
      "range_text": "0.3\u20139.8"
    },
    "Vitamin B5 (Pantothenic)": {
      "value": 73.74,
      "date": "May '25",
      "date_iso": "2025-05-01",
      "status": "in_range",
      "unit": "ng/mL",
      "range_text": "11\u2013150"
    },
    "Vitamin B6 (P5P)": {
      "value": 13.24,
      "date": "May '25",
      "date_iso": "2025-05-01",
      "status": "in_range",
      "unit": "ng/mL",
      "range_text": "5\u201350"
    },
    "Vitamin B7 (Biotin)": {
      "value": 3.79,
      "date": "May '25",
      "date_iso": "2025-05-01",
      "status": "high",
      "unit": "ng/mL",
      "range_text": "0.2\u20133"
    },
    "Vitamin B9 (Folic Acid)": {
      "value": 0.49,
      "date": "May '25",
      "date_iso": "2025-05-01",
      "status": "in_range",
      "unit": "ng/mL",
      "range_text": "0.2\u201320"
    },
    "Sodium": {
      "value": 144.0,
      "date": "Jan '26",
      "date_iso": "2026-01-01",
      "status": "in_range",
      "unit": "mmol/L",
      "range_text": "136\u2013145"
    },
    "Potassium": {
      "value": 5.1,
      "date": "Jan '26",
      "date_iso": "2026-01-01",
      "status": "in_range",
      "unit": "mmol/L",
      "range_text": "3.5\u20135.1"
    },
    "Chloride": {
      "value": 104.0,
      "date": "Jan '26",
      "date_iso": "2026-01-01",
      "status": "in_range",
      "unit": "mmol/L",
      "range_text": "98\u2013107"
    },
    "Calcium": {
      "value": 10.1,
      "date": "Jan '26",
      "date_iso": "2026-01-01",
      "status": "in_range",
      "unit": "mg/dL",
      "range_text": "8.5\u201310.2"
    },
    "Magnesium": {
      "value": 1.9,
      "date": "Jan '26",
      "date_iso": "2026-01-01",
      "status": "in_range",
      "unit": "mg/dL",
      "range_text": "1.6\u20132.6"
    },
    "Phosphorus": {
      "value": 4.3,
      "date": "Jan '26",
      "date_iso": "2026-01-01",
      "status": "in_range",
      "unit": "mg/dL",
      "range_text": "2.4\u20135.1"
    },
    "Bicarbonate": {
      "value": 24.4,
      "date": "Jun '23",
      "date_iso": "2023-06-01",
      "status": "in_range",
      "unit": "mmol/L",
      "range_text": "20\u201331"
    },
    "Selenium": {
      "value": 198.86,
      "date": "May '25",
      "date_iso": "2025-05-01",
      "status": "high",
      "unit": "\u00b5g/L",
      "range_text": "70\u2013150"
    },
    "hs-CRP": {
      "value": 1.545,
      "date": "Jan '26",
      "date_iso": "2026-01-01",
      "status": "in_range",
      "unit": "mg/L",
      "range_text": "<3.0"
    },
    "Anti-CCP (ACCP)": {
      "value": 0.5,
      "date": "May '25",
      "date_iso": "2025-05-01",
      "status": "in_range",
      "unit": "U/mL",
      "range_text": "<5"
    },
    "ANA": {
      "value": 7.16,
      "date": "May '25",
      "date_iso": "2025-05-01",
      "status": "in_range",
      "unit": "AU/mL",
      "range_text": "<50"
    },
    "Alpha-1-Antitrypsin": {
      "value": 126.7,
      "date": "May '25",
      "date_iso": "2025-05-01",
      "status": "in_range",
      "unit": "mg/dL",
      "range_text": "90\u2013200"
    },
    "Amylase": {
      "value": 64.4,
      "date": "May '25",
      "date_iso": "2025-05-01",
      "status": "in_range",
      "unit": "U/L",
      "range_text": "28\u2013100"
    },
    "Lipase": {
      "value": 27.8,
      "date": "May '25",
      "date_iso": "2025-05-01",
      "status": "in_range",
      "unit": "U/L",
      "range_text": "5.6\u201351.3"
    },
    "EHEC (Enterohemorrhagic E. coli)": {
      "value": 8.79,
      "date": "May 2025",
      "date_iso": "2025-05-01",
      "status": "high",
      "unit": "",
      "range_text": "<1e3"
    },
    "Blastocystis hominis": {
      "value": 2.7,
      "date": "May 2025",
      "date_iso": "2025-05-01",
      "status": "high",
      "unit": "",
      "range_text": "<2e3"
    },
    "Bacteroides fragilis": {
      "value": 2.17,
      "date": "May 2025",
      "date_iso": "2025-05-01",
      "status": "in_range",
      "unit": "",
      "range_text": "1.6e9\u20132.5e11"
    },
    "Bifidobacterium spp.": {
      "value": 6.3,
      "date": "May 2025",
      "date_iso": "2025-05-01",
      "status": "low",
      "unit": "",
      "range_text": ">6.7e7"
    },
    "Enterococcus spp.": {
      "value": 3.61,
      "date": "May 2025",
      "date_iso": "2025-05-01",
      "status": "in_range",
      "unit": "",
      "range_text": "1.9e5\u20132.0e8"
    },
    "Escherichia spp.": {
      "value": 6.19,
      "date": "May 2025",
      "date_iso": "2025-05-01",
      "status": "high",
      "unit": "",
      "range_text": "3.7e6\u20133.8e9"
    },
    "Lactobacillus spp.": {
      "value": 7.43,
      "date": "May 2025",
      "date_iso": "2025-05-01",
      "status": "low",
      "unit": "",
      "range_text": "8.6e5\u20136.2e8"
    },
    "Enterobacter spp.": {
      "value": 6.41,
      "date": "May 2025",
      "date_iso": "2025-05-01",
      "status": "high",
      "unit": "",
      "range_text": "1.0e6\u20135.0e7"
    },
    "Akkermansia muciniphila": {
      "value": 1.0,
      "date": "May 2025",
      "date_iso": "2025-05-01",
      "status": "in_range",
      "unit": "",
      "range_text": "1e1\u20138.2e6"
    },
    "Faecalibacterium prausnitzii": {
      "value": 2.21,
      "date": "May 2025",
      "date_iso": "2025-05-01",
      "status": "in_range",
      "unit": "",
      "range_text": "1e3\u20135e8"
    },
    "Roseburia spp.": {
      "value": 1.62,
      "date": "May 2025",
      "date_iso": "2025-05-01",
      "status": "low",
      "unit": "",
      "range_text": "5e7\u20132e10"
    },
    "Pseudomonas spp.": {
      "value": 1.22,
      "date": "May 2025",
      "date_iso": "2025-05-01",
      "status": "high",
      "unit": "",
      "range_text": "<1e4"
    },
    "Pseudomonas aeruginosa": {
      "value": 4.72,
      "date": "May 2025",
      "date_iso": "2025-05-01",
      "status": "in_range",
      "unit": "",
      "range_text": "<5e2"
    },
    "Klebsiella spp.": {
      "value": 1.56,
      "date": "May 2025",
      "date_iso": "2025-05-01",
      "status": "in_range",
      "unit": "",
      "range_text": "<5e3"
    },
    "Klebsiella pneumoniae": {
      "value": 1.71,
      "date": "May 2025",
      "date_iso": "2025-05-01",
      "status": "in_range",
      "unit": "",
      "range_text": "<5e4"
    },
    "Streptococcus spp.": {
      "value": 9.73,
      "date": "May 2025",
      "date_iso": "2025-05-01",
      "status": "high",
      "unit": "",
      "range_text": "<1e3"
    },
    "Bacillus spp.": {
      "value": 3.61,
      "date": "May 2025",
      "date_iso": "2025-05-01",
      "status": "high",
      "unit": "",
      "range_text": "<1.5e5"
    },
    "Enterococcus faecium": {
      "value": 6.11,
      "date": "May 2025",
      "date_iso": "2025-05-01",
      "status": "high",
      "unit": "",
      "range_text": "<1e4"
    },
    "Staphylococcus aureus": {
      "value": 1.75,
      "date": "May 2025",
      "date_iso": "2025-05-01",
      "status": "in_range",
      "unit": "",
      "range_text": "<5e2"
    },
    "Citrobacter freundii": {
      "value": 4.6,
      "date": "May 2025",
      "date_iso": "2025-05-01",
      "status": "in_range",
      "unit": "",
      "range_text": "<5e5"
    },
    "Fusobacterium spp.": {
      "value": 2.49,
      "date": "May 2025",
      "date_iso": "2025-05-01",
      "status": "high",
      "unit": "",
      "range_text": "<1e8"
    },
    "Prevotella spp.": {
      "value": 5.59,
      "date": "May 2025",
      "date_iso": "2025-05-01",
      "status": "high",
      "unit": "",
      "range_text": "<1e8"
    },
    "Bacteroidetes": {
      "value": 1.61,
      "date": "May 2025",
      "date_iso": "2025-05-01",
      "status": "low",
      "unit": "",
      "range_text": "8.6e11\u20133.3e12"
    },
    "Firmicutes": {
      "value": 6.05,
      "date": "May 2025",
      "date_iso": "2025-05-01",
      "status": "in_range",
      "unit": "",
      "range_text": "5.7e10\u20133.0e11"
    },
    "Firmicutes:Bacteroidetes": {
      "value": 0.37,
      "date": "May 2025",
      "date_iso": "2025-05-01",
      "status": "in_range",
      "unit": "",
      "range_text": "<1.0"
    },
    "Elastase-1": {
      "value": 109.0,
      "date": "May 2025",
      "date_iso": "2025-05-01",
      "status": "low",
      "unit": "",
      "range_text": ">200 \u00b5g/g"
    },
    "\u03b2-Glucuronidase": {
      "value": 2147.0,
      "date": "May 2025",
      "date_iso": "2025-05-01",
      "status": "in_range",
      "unit": "",
      "range_text": "<2486 U/mL"
    },
    "Occult Blood (FIT)": {
      "value": 0.0,
      "date": "May 2025",
      "date_iso": "2025-05-01",
      "status": "in_range",
      "unit": "",
      "range_text": "<10 \u00b5g/g"
    },
    "Secretory IgA": {
      "value": 210.0,
      "date": "May 2025",
      "date_iso": "2025-05-01",
      "status": "low",
      "unit": "",
      "range_text": "510\u20132010 \u00b5g/g"
    },
    "Anti-gliadin IgA": {
      "value": 24.0,
      "date": "May 2025",
      "date_iso": "2025-05-01",
      "status": "in_range",
      "unit": "",
      "range_text": "<175 U/L"
    },
    "Calprotectin": {
      "value": 0.0,
      "date": "May 2025",
      "date_iso": "2025-05-01",
      "status": "in_range",
      "unit": "",
      "range_text": "<173 \u00b5g/g"
    },
    "Eosinophil Activation (EDN)": {
      "value": 0.54,
      "date": "May 2025",
      "date_iso": "2025-05-01",
      "status": "in_range",
      "unit": "",
      "range_text": "<2.34 \u00b5g/g"
    },
    "Zonulin": {
      "value": 22.1,
      "date": "May 2025",
      "date_iso": "2025-05-01",
      "status": "in_range",
      "unit": "",
      "range_text": "<175 ng/g"
    },
    "pH": {
      "value": 6.0,
      "date": "May '25",
      "date_iso": "2025-05-01",
      "status": null,
      "unit": "",
      "range_text": ""
    },
    "Specific Gravity": {
      "value": 1.015,
      "date": "May '25",
      "date_iso": "2025-05-01",
      "status": null,
      "unit": "",
      "range_text": ""
    },
    "Microalbumin": {
      "value": 8.3,
      "date": "May '25",
      "date_iso": "2025-05-01",
      "status": null,
      "unit": "",
      "range_text": ""
    },
    "Urine Creatinine": {
      "value": 65.66,
      "date": "May '25",
      "date_iso": "2025-05-01",
      "status": null,
      "unit": "",
      "range_text": ""
    },
    "Albumin/Creatinine Ratio": {
      "value": 12.6,
      "date": "May '25",
      "date_iso": "2025-05-01",
      "status": null,
      "unit": "",
      "range_text": ""
    }
  },
  "active_conditions": [
    "Hashimoto's Thyroiditis (autoimmune hypothyroidism)",
    "Low Testosterone (Hypogonadism)",
    "Grade I Fatty Liver",
    "MTHFR A1298C Homozygous Mutation",
    "Borderline Insulin Resistance",
    "Radial Nerve Injury (Right Tricep)"
  ],
  "active_meds": [
    "Thyroid (compounded NDT \u2014 Bella Sante)",
    "Retatrutide (GLP-1/GIP/glucagon triple agonist)"
  ],
  "treatment_goals": [
    "TSH",
    "Total Testosterone",
    "Body Weight",
    "Body Fat %",
    "Muscle Mass",
    "Fatty Liver",
    "Gut Health"
  ],
  "active_concerns": [
    "Weight trajectory",
    "HRV",
    "Sleep",
    "Body composition",
    "TSH improvement",
    "Testosterone trajectory",
    "Strength capacity",
    "Retatrutide effects",
    "Liver markers",
    "Insulin resistance"
  ],
  "baselines_30d_90d": {
    "hrv_30d_avg": 40.58,
    "hrv_p5": 22.36,
    "hrv_p95": 51.72,
    "rhr_30d_avg": 64.95,
    "rhr_p5": 61,
    "rhr_p95": 77,
    "recovery_30d_avg": 46.64,
    "recovery_p5": 16,
    "recovery_p95": 85,
    "sleep_total_h_30d_avg": 5.41,
    "sleep_total_h_p5": 3.54,
    "sleep_total_h_p95": 7.17,
    "deep_h_30d_avg": 1.47,
    "deep_h_p5": 0.76,
    "deep_h_p95": 1.94
  },
  "gaps": [
    "No Whoop data for 2026-04-20",
    "No health log for 2026-04-20",
    "No health log for 2026-04-21",
    "No health log for 2026-04-22",
    "No health log for 2026-04-23",
    "No health log for 2026-04-24"
  ],
  "days_since_blood": 120,
  "days_since_thyroid": 61,
  "previous_week_summary": {
    "verdict": "Sleep is the bottleneck this week \u2014 5.71h average against 13.7h cumulative debt, layered on a thyroid that's still underdosed (TSH 6.654, last checked 61 days ago) and four padel sessions on a 1.13 strain:recovery ratio. Saturday's 24% recovery wasn't a bad night; it was the autonomic price of stacking training on inadequate repair. Cap padel at 2 sessions next week, protect 7+ hours in bed nightly until the debt closes, and book the thyroid retest now.",
    "top_actions": [
      "[Medical \u00b7 This week] Book a full thyroid panel (TSH, fT3, fT4, rT3, anti-TPO) \u2014 61 days since last, NDT dose review is overdue with TSH still 6.654.",
      "[Sleep \u00b7 Tonight] 7+ hours in bed every night until the 13.7h sleep debt closes \u2014 lights out by 10:30 PM, phone out of the bedroom.",
      "[Training \u00b7 This week] Cap padel at 2 sessions and replace one with structured resistance training to defend lean mass on retatrutide."
    ]
  }
};

window.WEEK_DATA = Object.assign({}, PARTIAL_DATA, {
  "verdict": "The autonomic price of last week persists: sleep debt frozen at 13.7h, padel at 4 sessions instead of the 2-session cap, thyroid retest now 61 days overdue. HRV is holding at 40.18 ms but that's reserve absorbing chronic underdosed thyroid plus undersleep — not adaptation, deferral. Book the panel this week, drop one padel, and floor 7h in bed nightly until the debt clears.",
  "bodySignals": [
    {
      "title": "Autonomic / Recovery — compensated, not adapted",
      "body": "HRV 40.18 ms (-1% vs 30d), RHR 65.67 (+0.7), CV 20.5%. Surface metrics stable, but stable on top of TSH 6.654 and 13.7h sleep debt is the body absorbing load, not handling it. Saturday's 24% recovery dropped without a heavy training event the day before — that's accumulated under-restoration crystallizing. Recovery distribution was 1 red / 3 amber / 2 green across 6 captured days, meaning amber-or-worse on 67% of measurements. The 20.5% HRV CV is sleep-timing variance, not autonomic noise."
    },
    {
      "title": "Sleep architecture — restricted, not improved",
      "body": "5.71h average, 92.64% efficiency, deep 1.55h (just over the 1.5h target), REM 1.6h. Cumulative debt 13.7h — identical to last week, despite the directive to floor 7h. Efficiency reads high because total time in bed is short; you're sleep-restricting, not sleep-improving. With Hashimoto's TSH at 6.654, sleep is the only lever still uncosted to offset thyroid-mediated fatigue — short total sleep amplifies it instead. Deep sleep meeting target is the one bright spot; total volume is the bottleneck."
    },
    {
      "title": "Training Load — buying sessions on credit",
      "body": "4 workouts, strain total 60.1, strain:recovery ratio 1.13. Last week's prescription was 2 padel sessions; this week ran 4. Ratio above 1.0 with recovery averaging 53.33% means each session is purchased on credit. Friday hitting 87 recovery shows the body produces a green day when input arrives; Saturday's 24 next door shows the cost when it doesn't. With Total Testosterone at 205 ng/dL (low, Nov '25) and retatrutide pulling caloric intake down, training above repair will pull from lean mass before fat — the worst possible direction on this protocol."
    },
    {
      "title": "Metabolic / Nutrition — undersupplied and underlogged",
      "body": "Protein averaged 64g across the 2 days that were logged, against a 120g target — zero hits. 5 of 7 days have no health log, so 64g is itself partial-data. With retatrutide suppressing appetite and Total T at 205, anything below 1.6 g/kg protein is a muscle-loss accelerator. Supplement compliance reads 2/2 on logged days (T3+T4 thyroid included) but the denominator is 2 of 7 — what you can't see, you can't manage. One alcohol day on Sunday shows up cleanly in Sunday's 41 recovery."
    }
  ],
  "connections": [
    {
      "title": "Underdosed thyroid + short sleep + flat HRV",
      "whoop": "HRV 40.18 ms (stable, -1% vs 30d), sleep 5.71h, debt 13.7h",
      "lab": "TSH 6.654 µIU/mL (Mar '26, 61 days old), Anti-TPO 354.6, Free T3 2.92 (low-mid)",
      "nutrition": "Protein 64g avg (partial), zero days at 120g target",
      "interpretation": "TSH at 1.4× upper limit means tissue-level hypothyroidism is unaddressed. The autonomic stability you're seeing is reserve, not function — sleep restriction on top of an underdosed thyroid plus a protein deficit compounds the substrate shortage for thyroid hormone synthesis and downstream repair. The body is holding only because nothing has acutely demanded more from it.",
      "action": "Book full thyroid panel (TSH, fT3, fT4, rT3, anti-TPO) this week. Last week flagged this — still not done. Bring the result to NDT dose review."
    },
    {
      "title": "Padel volume + protein deficit + low Testosterone + retatrutide",
      "whoop": "4 workouts, strain 60.1, strain:recovery 1.13, recovery dist 1R/3A/2G",
      "lab": "Total Testosterone 205 ng/dL (low, Nov '25), Free T 16.8 (low-end)",
      "nutrition": "Protein 64g avg, 0/7 target hits, retatrutide active",
      "interpretation": "Training above recovery + protein <1.6 g/kg + suppressed androgens + retatrutide caloric pressure is a textbook lean-mass-loss combination. Body composition concerns on this protocol depend entirely on the protein floor and the strain cap; both are missed.",
      "action": "Drop one padel session this week and replace it with resistance training. Floor 120g protein on training days via post-workout shake if appetite is suppressed."
    },
    {
      "title": "Saturday red recovery + Sunday alcohol + fatty liver context",
      "whoop": "Sat recovery 24 (red, no event), Sun 41 (amber, alcohol)",
      "lab": "Grade I fatty liver, ALT 39 (upper-mid in range), GGT 42, Triglycerides 127",
      "nutrition": "1 alcohol day (Sunday)",
      "interpretation": "Saturday's 24 came before the drink — that's cumulative undersupply from the week, not the alcohol. But the Sunday drink registered cleanly as a -46-point recovery hit and is meaningful for fatty liver while ALT is still 39. Weekly alcohol is incompatible with the fatty-liver treatment goal listed in the profile.",
      "action": "Zero alcohol for the next 4 weeks. Re-check ALT, GGT, triglycerides at the upcoming blood panel."
    },
    {
      "title": "Health-log capture gap + carry-over of last week's same gap",
      "whoop": "Whoop captured 6/7 days",
      "lab": "n/a",
      "nutrition": "Only Apr 25 and Apr 26 logged; Apr 20–24 missing",
      "interpretation": "The capture gap is the single biggest blocker to using this dashboard — protein, supplement, and alcohol patterns can't be inferred from Whoop. Last week's recommendation set was built on similar partial data; this week the pattern repeated.",
      "action": "Log nutrition + supplement intake at the evening RYD debrief, every day. Backfill the missing 5 days tonight while the week is still recoverable."
    }
  ],
  "actions": [
    {
      "priority": 1,
      "category": "Medical",
      "timeframe": "This week",
      "text": "Book thyroid panel (TSH, fT3, fT4, rT3, anti-TPO) — 61 days since last, second consecutive week this has been flagged."
    },
    {
      "priority": 2,
      "category": "Sleep",
      "timeframe": "Tonight",
      "text": "Lights out by 10:30 PM, phone out of the bedroom — every night until the 13.7h debt closes, no exceptions."
    },
    {
      "priority": 3,
      "category": "Training",
      "timeframe": "This week",
      "text": "Cap padel at 2 sessions; replace one with structured resistance training to defend lean mass on retatrutide and low T."
    },
    {
      "priority": 4,
      "category": "Nutrition",
      "timeframe": "Tonight",
      "text": "Floor 120g protein daily; whey shake post-workout when appetite is suppressed by retatrutide."
    },
    {
      "priority": 5,
      "category": "Nutrition",
      "timeframe": "This week",
      "text": "Zero alcohol for the next 4 weeks while fatty-liver markers (ALT 39, GGT 42) heal."
    },
    {
      "priority": 6,
      "category": "Medical",
      "timeframe": "Within 2 weeks",
      "text": "Schedule full panel — 120 days since last (CBC, LFT, lipids, fasting insulin/glucose, hs-CRP)."
    },
    {
      "priority": 7,
      "category": "Supplements",
      "timeframe": "Tonight",
      "text": "Capture nutrition + supplement intake in tonight's RYD debrief; backfill the missing 5 days."
    }
  ]
});
