// Auto-generated by weekly-health-briefing/starter.py
// Deterministic fields. Verdict, bodySignals, connections, actions are appended at runtime.
const PARTIAL_DATA = {
  "patient": {
    "name": "Pratik",
    "age": 42,
    "week": "Week ending Apr 30, 2026",
    "dateRange": "Apr 24 \u2014 Apr 30, 2026"
  },
  "days": [
    {
      "day": "Fri",
      "date": "Apr 24",
      "recovery": {
        "score": 87,
        "hrv": 50.886986,
        "rhr": 64,
        "spo2": 96.1,
        "skinTemp": 34.11779
      },
      "sleep": {
        "total": 7.25,
        "deep": 1.58,
        "rem": 2.28,
        "light": 3.39,
        "eff": 94.56865,
        "perf": 84,
        "cons": 81,
        "rr": 14.765625,
        "dist": 22,
        "needed": 9.67,
        "debt": 2.13
      },
      "strain": {
        "score": 17.14685,
        "kj": 13805.713,
        "avg": 81,
        "max": 179
      },
      "workout": {
        "sport": "Workout",
        "min": 0,
        "strain": 15.565295,
        "avg": 144,
        "max": 179,
        "kj": 3800.8044
      },
      "food": {
        "dinner": "\u2014",
        "late": false,
        "alcohol": 0,
        "skipped": null,
        "lastMeal": "\u2014"
      },
      "supps": {
        "taken": 0,
        "missed": [],
        "total": 0
      },
      "is_gap": false
    },
    {
      "day": "Sat",
      "date": "Apr 25",
      "recovery": {
        "score": 24,
        "hrv": 36.8135,
        "rhr": 66,
        "spo2": 96,
        "skinTemp": 34.215668
      },
      "sleep": {
        "total": 3.63,
        "deep": 1.31,
        "rem": 0.92,
        "light": 1.4,
        "eff": 98.639885,
        "perf": 40,
        "cons": 76,
        "rr": 14.765625,
        "dist": 4,
        "needed": 9.91,
        "debt": 1.55
      },
      "strain": {
        "score": 4.255712,
        "kj": 8189.8267,
        "avg": 72,
        "max": 130
      },
      "workout": null,
      "food": {
        "dinner": "Salad, 1 sandwich with coleslaw",
        "late": false,
        "alcohol": 0,
        "skipped": null,
        "lastMeal": "\u2014"
      },
      "supps": {
        "taken": 12,
        "missed": [
          "Omega 3",
          "Myo inositol + Collagen + EAA Thorne",
          "Colostrum",
          "TMG",
          "Zinc",
          "Probiotics",
          "Magnesium Bisglycinate",
          "Black seed oil"
        ],
        "total": 20
      },
      "is_gap": false
    },
    {
      "day": "Sun",
      "date": "Apr 26",
      "recovery": {
        "score": 41,
        "hrv": 31.342546,
        "rhr": 68,
        "spo2": 97.4,
        "skinTemp": 34.349335
      },
      "sleep": {
        "total": 6.12,
        "deep": 1.48,
        "rem": 1.68,
        "light": 2.96,
        "eff": 90.17126,
        "perf": 75,
        "cons": 69,
        "rr": 14.941406,
        "dist": 16,
        "needed": 9.67,
        "debt": 2.13
      },
      "strain": {
        "score": 5.965974,
        "kj": 8612.794,
        "avg": 74,
        "max": 165
      },
      "workout": null,
      "food": {
        "dinner": "Rice and Asian curry, veg sushi",
        "late": false,
        "alcohol": 2,
        "skipped": null,
        "lastMeal": "\u2014",
        "note": "2 sake shots"
      },
      "supps": {
        "taken": 1,
        "missed": [
          "Liposomal Glutathione",
          "Magnesium + salt water",
          "Digestive enzymes",
          "Vit D3+K2",
          "B complex",
          "Omega 3",
          "Shilajit",
          "DHEAs",
          "Myo inositol + Collagen + EAA Thorne",
          "Colostrum",
          "Lactoferrin",
          "Nato Serra",
          "T3 thyroid medication",
          "TMG",
          "Zinc",
          "Probiotics",
          "Magnesium Bisglycinate",
          "Black seed oil",
          "Detox Binder"
        ],
        "total": 20
      },
      "is_gap": false
    },
    {
      "day": "Mon",
      "date": "Apr 27",
      "recovery": {
        "score": 0,
        "hrv": 0,
        "rhr": 0,
        "spo2": 0,
        "skinTemp": 0
      },
      "sleep": {
        "total": 0,
        "deep": 0,
        "rem": 0,
        "light": 0,
        "eff": 0,
        "perf": 0,
        "cons": 0,
        "rr": 0,
        "dist": 0,
        "needed": 0,
        "debt": 0
      },
      "strain": {
        "score": 0,
        "kj": 0,
        "avg": 0,
        "max": 0
      },
      "workout": null,
      "food": {
        "dinner": "Chicken tikka",
        "late": false,
        "alcohol": 0,
        "skipped": null,
        "lastMeal": "\u2014"
      },
      "supps": {
        "taken": 6,
        "missed": [
          "Liposomal Glutathione",
          "Magnesium + salt water",
          "Digestive enzymes",
          "Vit D3+K2",
          "Omega 3",
          "Myo inositol + Collagen + EAA Thorne",
          "Colostrum",
          "Lactoferrin",
          "Nato Serra",
          "TMG",
          "Zinc",
          "Probiotics",
          "Magnesium Bisglycinate",
          "Black seed oil"
        ],
        "total": 20
      },
      "is_gap": true
    },
    {
      "day": "Tue",
      "date": "Apr 28",
      "recovery": {
        "score": 0,
        "hrv": 0,
        "rhr": 0,
        "spo2": 0,
        "skinTemp": 0
      },
      "sleep": {
        "total": 0,
        "deep": 0,
        "rem": 0,
        "light": 0,
        "eff": 0,
        "perf": 0,
        "cons": 0,
        "rr": 0,
        "dist": 0,
        "needed": 0,
        "debt": 0
      },
      "strain": {
        "score": 0,
        "kj": 0,
        "avg": 0,
        "max": 0
      },
      "workout": null,
      "food": {
        "dinner": "\u2014",
        "late": false,
        "alcohol": 0,
        "skipped": null,
        "lastMeal": "\u2014"
      },
      "supps": {
        "taken": 0,
        "missed": [],
        "total": 0
      },
      "is_gap": true
    },
    {
      "day": "Wed",
      "date": "Apr 29",
      "recovery": {
        "score": 0,
        "hrv": 0,
        "rhr": 0,
        "spo2": 0,
        "skinTemp": 0
      },
      "sleep": {
        "total": 0,
        "deep": 0,
        "rem": 0,
        "light": 0,
        "eff": 0,
        "perf": 0,
        "cons": 0,
        "rr": 0,
        "dist": 0,
        "needed": 0,
        "debt": 0
      },
      "strain": {
        "score": 0,
        "kj": 0,
        "avg": 0,
        "max": 0
      },
      "workout": null,
      "food": {
        "dinner": "Beetroot salad with walnuts, 2 boiled eggs",
        "late": false,
        "alcohol": 0,
        "skipped": null,
        "lastMeal": "\u2014"
      },
      "supps": {
        "taken": 7,
        "missed": [
          "Liposomal Glutathione",
          "Magnesium + salt water",
          "Digestive enzymes",
          "Vit D3+K2",
          "Omega 3",
          "Myo inositol + Collagen + EAA Thorne",
          "Colostrum",
          "Lactoferrin",
          "Nato Serra",
          "TMG",
          "Zinc",
          "Probiotics",
          "Black seed oil"
        ],
        "total": 20
      },
      "is_gap": true
    },
    {
      "day": "Thu",
      "date": "Apr 30",
      "recovery": {
        "score": 0,
        "hrv": 0,
        "rhr": 0,
        "spo2": 0,
        "skinTemp": 0
      },
      "sleep": {
        "total": 0,
        "deep": 0,
        "rem": 0,
        "light": 0,
        "eff": 0,
        "perf": 0,
        "cons": 0,
        "rr": 0,
        "dist": 0,
        "needed": 0,
        "debt": 0
      },
      "strain": {
        "score": 0,
        "kj": 0,
        "avg": 0,
        "max": 0
      },
      "workout": null,
      "food": {
        "dinner": "1 slice pizza, edamame and avocado salad cup, small rice with curry (dinner at Rikin & Priyanka's)",
        "late": false,
        "alcohol": 0,
        "skipped": null,
        "lastMeal": "\u2014"
      },
      "supps": {
        "taken": 1,
        "missed": [
          "Liposomal Glutathione",
          "Magnesium + salt water",
          "Digestive enzymes",
          "Vit D3+K2",
          "B complex",
          "Omega 3",
          "Shilajit",
          "DHEAs",
          "Myo inositol + Collagen + EAA Thorne",
          "Colostrum",
          "Lactoferrin",
          "Nato Serra",
          "T3 thyroid medication",
          "TMG",
          "Zinc",
          "Probiotics",
          "Magnesium Bisglycinate",
          "Black seed oil",
          "Detox Binder"
        ],
        "total": 20
      },
      "is_gap": true
    }
  ],
  "derived": {
    "hrvAvg7d": 39.68,
    "hrvAvg30d": 40.58,
    "hrvDeltaPct": -2.2,
    "hrvCv": 25.4,
    "hrvTrend": "declining",
    "hrv4wkTrend": [
      39.68,
      39.68,
      39.68,
      40.68,
      39.68
    ],
    "rhrAvg7d": 66,
    "rhrAvg30d": 64.95,
    "rhrTrend": "rising",
    "rhr4wkTrend": [
      66,
      66,
      66,
      65.33,
      66
    ],
    "recoveryAvg7d": 51,
    "recoveryAvg30d": 47,
    "recoveryBand": [
      16,
      85
    ],
    "recovery4wkTrend": [
      50.67,
      50.67,
      50.67,
      56,
      50.67
    ],
    "sleepDebt4wkTrend": [
      7.0,
      7.0,
      7.0,
      6.07,
      7.0
    ],
    "deepAvg7d": 1.46,
    "deepTarget": 1.5,
    "sleepDebtCum": 7.0,
    "sleepBand": [
      3.54,
      7.17
    ],
    "deepBand": [
      0.76,
      1.94
    ],
    "hrvBand": [
      22.36,
      51.72
    ],
    "rhrBand": [
      61,
      77
    ],
    "strainRecRatio": 0.54,
    "totalStrain": 27.4,
    "padelSessions": 2,
    "daysSinceBlood": 120,
    "daysSinceThyroid": 61,
    "proteinAvg30d": 0,
    "proteinTarget": 120,
    "caloriesAvg30d": 0,
    "carbsAvg30d": 0,
    "fatAvg30d": 0,
    "lateDinners30d": 0.0,
    "alcoholDays30d": 0.0,
    "suppsAvg30d": 0,
    "suppsTotalsByCategory": {
      "critical": {
        "taken": 8,
        "total": 10
      },
      "adjunct": {
        "taken": 19,
        "total": 90
      },
      "overall": {
        "taken": 27,
        "total": 100
      }
    }
  },
  "nutrition": [
    {
      "day": "Fri",
      "date": "Apr 24",
      "cal": 0,
      "protein": 0,
      "carbs": 0,
      "fat": 0,
      "lastMeal": "\u2014",
      "late": false,
      "alcohol": 0,
      "flags": []
    },
    {
      "day": "Sat",
      "date": "Apr 25",
      "cal": 1135,
      "protein": 90,
      "carbs": 68,
      "fat": 58,
      "lastMeal": "\u2014",
      "late": false,
      "alcohol": 0,
      "flags": []
    },
    {
      "day": "Sun",
      "date": "Apr 26",
      "cal": 1080,
      "protein": 38,
      "carbs": 182,
      "fat": 22,
      "lastMeal": "\u2014",
      "late": false,
      "alcohol": 2,
      "flags": [
        "alcohol"
      ]
    },
    {
      "day": "Mon",
      "date": "Apr 27",
      "cal": 545,
      "protein": 39,
      "carbs": 80,
      "fat": 8,
      "lastMeal": "\u2014",
      "late": false,
      "alcohol": 0,
      "flags": []
    },
    {
      "day": "Tue",
      "date": "Apr 28",
      "cal": 0,
      "protein": 0,
      "carbs": 0,
      "fat": 0,
      "lastMeal": "\u2014",
      "late": false,
      "alcohol": 0,
      "flags": []
    },
    {
      "day": "Wed",
      "date": "Apr 29",
      "cal": 605,
      "protein": 69,
      "carbs": 34,
      "fat": 20,
      "lastMeal": "\u2014",
      "late": false,
      "alcohol": 0,
      "flags": []
    },
    {
      "day": "Thu",
      "date": "Apr 30",
      "cal": 1035,
      "protein": 54,
      "carbs": 108,
      "fat": 44,
      "lastMeal": "\u2014",
      "late": false,
      "alcohol": 0,
      "flags": []
    }
  ],
  "bloods": [
    {
      "marker": "TSH",
      "value": 6.654,
      "unit": "\u00b5IU/mL",
      "range": "0.4\u20134.78",
      "status": "high",
      "sev": "amber"
    },
    {
      "marker": "FT3",
      "value": 2.92,
      "unit": "pg/mL",
      "range": "2.0\u20134.4",
      "status": "in_range",
      "sev": "green"
    },
    {
      "marker": "FT4",
      "value": 1.11,
      "unit": "ng/dL",
      "range": "0.89\u20131.76",
      "status": "in_range",
      "sev": "green"
    },
    {
      "marker": "Testosterone",
      "value": 205.0,
      "unit": "ng/dL",
      "range": "249\u2013836",
      "status": "low",
      "sev": "red"
    },
    {
      "marker": "Fasting Insulin",
      "value": 13.0,
      "unit": "\u00b5IU/mL",
      "range": "2\u201325",
      "status": "in_range",
      "sev": "green"
    },
    {
      "marker": "HbA1c",
      "value": 5.6,
      "unit": "%",
      "range": "<5.7",
      "status": "in_range",
      "sev": "green"
    },
    {
      "marker": "Glucose (FS)",
      "value": 99.0,
      "unit": "mg/dL",
      "range": "70\u2013100",
      "status": "in_range",
      "sev": "green"
    },
    {
      "marker": "LDL",
      "value": 156.6,
      "unit": "mg/dL",
      "range": "<100",
      "status": "high",
      "sev": "red"
    },
    {
      "marker": "HDL",
      "value": 41.0,
      "unit": "mg/dL",
      "range": ">40",
      "status": "in_range",
      "sev": "green"
    },
    {
      "marker": "ApoB",
      "value": 132.0,
      "unit": "mg/dL",
      "range": "56\u2013145",
      "status": "in_range",
      "sev": "green"
    },
    {
      "marker": "Homocysteine",
      "value": 8.48,
      "unit": "\u00b5mol/L",
      "range": "<15",
      "status": "in_range",
      "sev": "green"
    },
    {
      "marker": "ESR",
      "value": 22.0,
      "unit": "mm/hr",
      "range": "0\u201315",
      "status": "high",
      "sev": "amber"
    }
  ],
  "conditions": [
    "Hashimoto's Thyroiditis (autoimmune hypothyroidism)",
    "Low Testosterone (Hypogonadism)",
    "Grade I Fatty Liver",
    "MTHFR A1298C Homozygous Mutation",
    "Borderline Insulin Resistance",
    "Radial Nerve Injury (Right Tricep)"
  ],
  "medications": [
    {
      "name": "Thyroid (compounded NDT \u2014 Bella Sante)",
      "dose": "T3 20mcg + T4 40mcg (1 pill)",
      "freq": "twice daily"
    },
    {
      "name": "Retatrutide (GLP-1/GIP/glucagon triple agonist)",
      "dose": "2000mcg weekly, Saturday morning",
      "freq": "weekly"
    }
  ],
  "supplements": [
    {
      "name": "T3+T4 thyroid medication",
      "taken": 5,
      "total": 5,
      "critical": true,
      "dayStatus": [
        "no-data",
        "taken",
        "taken",
        "taken",
        "no-data",
        "taken",
        "taken"
      ]
    },
    {
      "name": "Liposomal Glutathione",
      "taken": 1,
      "total": 5,
      "critical": false,
      "missedDays": [
        "Sun",
        "Mon",
        "Wed",
        "Thu"
      ],
      "dayStatus": [
        "no-data",
        "taken",
        "missed",
        "missed",
        "no-data",
        "missed",
        "missed"
      ]
    },
    {
      "name": "Creatine",
      "taken": 0,
      "total": 0,
      "critical": false,
      "dayStatus": [
        "no-data",
        "no-data",
        "no-data",
        "no-data",
        "no-data",
        "no-data",
        "no-data"
      ]
    },
    {
      "name": "Magnesium + salt water",
      "taken": 1,
      "total": 5,
      "critical": false,
      "missedDays": [
        "Sun",
        "Mon",
        "Wed",
        "Thu"
      ],
      "dayStatus": [
        "no-data",
        "taken",
        "missed",
        "missed",
        "no-data",
        "missed",
        "missed"
      ]
    },
    {
      "name": "Digestive enzymes",
      "taken": 1,
      "total": 5,
      "critical": false,
      "missedDays": [
        "Sun",
        "Mon",
        "Wed",
        "Thu"
      ],
      "dayStatus": [
        "no-data",
        "taken",
        "missed",
        "missed",
        "no-data",
        "missed",
        "missed"
      ]
    },
    {
      "name": "Vit D3+K2",
      "taken": 1,
      "total": 5,
      "critical": false,
      "missedDays": [
        "Sun",
        "Mon",
        "Wed",
        "Thu"
      ],
      "dayStatus": [
        "no-data",
        "taken",
        "missed",
        "missed",
        "no-data",
        "missed",
        "missed"
      ]
    },
    {
      "name": "B complex",
      "taken": 3,
      "total": 5,
      "critical": false,
      "missedDays": [
        "Sun",
        "Thu"
      ],
      "dayStatus": [
        "no-data",
        "taken",
        "missed",
        "taken",
        "no-data",
        "taken",
        "missed"
      ]
    },
    {
      "name": "Omega 3",
      "taken": 0,
      "total": 5,
      "critical": false,
      "missedDays": [
        "Sat",
        "Sun",
        "Mon",
        "Wed",
        "Thu"
      ],
      "dayStatus": [
        "no-data",
        "missed",
        "missed",
        "missed",
        "no-data",
        "missed",
        "missed"
      ]
    },
    {
      "name": "Shilajit",
      "taken": 3,
      "total": 5,
      "critical": false,
      "missedDays": [
        "Sun",
        "Thu"
      ],
      "dayStatus": [
        "no-data",
        "taken",
        "missed",
        "taken",
        "no-data",
        "taken",
        "missed"
      ]
    },
    {
      "name": "DHEAs",
      "taken": 3,
      "total": 5,
      "critical": false,
      "missedDays": [
        "Sun",
        "Thu"
      ],
      "dayStatus": [
        "no-data",
        "taken",
        "missed",
        "taken",
        "no-data",
        "taken",
        "missed"
      ]
    },
    {
      "name": "Myo inositol + Collagen + EAA Thorne",
      "taken": 0,
      "total": 5,
      "critical": false,
      "missedDays": [
        "Sat",
        "Sun",
        "Mon",
        "Wed",
        "Thu"
      ],
      "dayStatus": [
        "no-data",
        "missed",
        "missed",
        "missed",
        "no-data",
        "missed",
        "missed"
      ]
    },
    {
      "name": "Colostrum",
      "taken": 0,
      "total": 5,
      "critical": false,
      "missedDays": [
        "Sat",
        "Sun",
        "Mon",
        "Wed",
        "Thu"
      ],
      "dayStatus": [
        "no-data",
        "missed",
        "missed",
        "missed",
        "no-data",
        "missed",
        "missed"
      ]
    },
    {
      "name": "Lactoferrin",
      "taken": 1,
      "total": 5,
      "critical": false,
      "missedDays": [
        "Sun",
        "Mon",
        "Wed",
        "Thu"
      ],
      "dayStatus": [
        "no-data",
        "taken",
        "missed",
        "missed",
        "no-data",
        "missed",
        "missed"
      ]
    },
    {
      "name": "Nato Serra",
      "taken": 1,
      "total": 5,
      "critical": false,
      "missedDays": [
        "Sun",
        "Mon",
        "Wed",
        "Thu"
      ],
      "dayStatus": [
        "no-data",
        "taken",
        "missed",
        "missed",
        "no-data",
        "missed",
        "missed"
      ]
    },
    {
      "name": "T3 thyroid medication",
      "taken": 3,
      "total": 5,
      "critical": true,
      "missedDays": [
        "Sun",
        "Thu"
      ],
      "dayStatus": [
        "no-data",
        "taken",
        "missed",
        "taken",
        "no-data",
        "taken",
        "missed"
      ]
    },
    {
      "name": "TMG",
      "taken": 0,
      "total": 5,
      "critical": false,
      "missedDays": [
        "Sat",
        "Sun",
        "Mon",
        "Wed",
        "Thu"
      ],
      "dayStatus": [
        "no-data",
        "missed",
        "missed",
        "missed",
        "no-data",
        "missed",
        "missed"
      ]
    },
    {
      "name": "Zinc",
      "taken": 0,
      "total": 5,
      "critical": false,
      "missedDays": [
        "Sat",
        "Sun",
        "Mon",
        "Wed",
        "Thu"
      ],
      "dayStatus": [
        "no-data",
        "missed",
        "missed",
        "missed",
        "no-data",
        "missed",
        "missed"
      ]
    },
    {
      "name": "Probiotics",
      "taken": 0,
      "total": 5,
      "critical": false,
      "missedDays": [
        "Sat",
        "Sun",
        "Mon",
        "Wed",
        "Thu"
      ],
      "dayStatus": [
        "no-data",
        "missed",
        "missed",
        "missed",
        "no-data",
        "missed",
        "missed"
      ]
    },
    {
      "name": "Magnesium Bisglycinate",
      "taken": 1,
      "total": 5,
      "critical": false,
      "missedDays": [
        "Sat",
        "Sun",
        "Mon",
        "Thu"
      ],
      "dayStatus": [
        "no-data",
        "missed",
        "missed",
        "missed",
        "no-data",
        "taken",
        "missed"
      ]
    },
    {
      "name": "Black seed oil",
      "taken": 0,
      "total": 5,
      "critical": false,
      "missedDays": [
        "Sat",
        "Sun",
        "Mon",
        "Wed",
        "Thu"
      ],
      "dayStatus": [
        "no-data",
        "missed",
        "missed",
        "missed",
        "no-data",
        "missed",
        "missed"
      ]
    },
    {
      "name": "Detox Binder",
      "taken": 3,
      "total": 5,
      "critical": false,
      "missedDays": [
        "Sun",
        "Thu"
      ],
      "dayStatus": [
        "no-data",
        "taken",
        "missed",
        "taken",
        "no-data",
        "taken",
        "missed"
      ]
    }
  ],
  "window": "Apr 24 \u2014 Apr 30, 2026",
  "window_start": "2026-04-24",
  "window_end": "2026-04-30",
  "generated_at": "2026-05-01T15:00:32.276839",
  "weekly_metrics": {
    "hrv_avg": 39.68,
    "hrv_cv": 25.4,
    "hrv_vs_30d_pct": -2.2,
    "hrv_trend": "declining",
    "rhr_avg": 66,
    "rhr_vs_30d": 1.0,
    "rhr_trend": "rising",
    "recovery_avg": 50.67,
    "recovery_distribution": {
      "red": 1,
      "amber": 1,
      "green": 1
    },
    "sleep_avg_h": 5.67,
    "deep_avg_h": 1.46,
    "deep_target_h": 1.5,
    "rem_avg_h": 1.63,
    "light_avg_h": 2.58,
    "efficiency_avg": 94.46,
    "sleep_debt_cum_h": 7.0,
    "strain_total": 27.4,
    "strain_recovery_ratio": 0.54,
    "padel_sessions": 2,
    "skin_temp_avg": 34.23,
    "rr_avg": 14.82,
    "supp_compliance": {
      "T3+T4 thyroid medication": "5/5 [critical-med]",
      "Liposomal Glutathione": "1/5 (missed Sun/Mon/Wed/Thu)",
      "Creatine": "no logs",
      "Magnesium + salt water": "1/5 (missed Sun/Mon/Wed/Thu)",
      "Digestive enzymes": "1/5 (missed Sun/Mon/Wed/Thu)",
      "Vit D3+K2": "1/5 (missed Sun/Mon/Wed/Thu)",
      "B complex": "3/5 (missed Sun/Thu)",
      "Omega 3": "0/5 (missed Sat/Sun/Mon/Wed/Thu)",
      "Shilajit": "3/5 (missed Sun/Thu)",
      "DHEAs": "3/5 (missed Sun/Thu)",
      "Myo inositol + Collagen + EAA Thorne": "0/5 (missed Sat/Sun/Mon/Wed/Thu)",
      "Colostrum": "0/5 (missed Sat/Sun/Mon/Wed/Thu)",
      "Lactoferrin": "1/5 (missed Sun/Mon/Wed/Thu)",
      "Nato Serra": "1/5 (missed Sun/Mon/Wed/Thu)",
      "T3 thyroid medication": "3/5 (missed Sun/Thu) [critical-med]",
      "TMG": "0/5 (missed Sat/Sun/Mon/Wed/Thu)",
      "Zinc": "0/5 (missed Sat/Sun/Mon/Wed/Thu)",
      "Probiotics": "0/5 (missed Sat/Sun/Mon/Wed/Thu)",
      "Magnesium Bisglycinate": "1/5 (missed Sat/Sun/Mon/Thu)",
      "Black seed oil": "0/5 (missed Sat/Sun/Mon/Wed/Thu)",
      "Detox Binder": "3/5 (missed Sun/Thu)"
    },
    "protein_avg_g": 58,
    "protein_target_hits": 0,
    "alcohol_days": 1,
    "late_dinners": 0,
    "skipped_meals": 0
  },
  "day_summaries": [
    {
      "day": "Fri",
      "date": "2026-04-24",
      "recovery": 87,
      "key_event": "Workout"
    },
    {
      "day": "Sat",
      "date": "2026-04-25",
      "recovery": 24,
      "key_event": "\u2014"
    },
    {
      "day": "Sun",
      "date": "2026-04-26",
      "recovery": 41,
      "key_event": "alcohol"
    },
    {
      "day": "Mon",
      "date": "2026-04-27",
      "recovery": null,
      "key_event": "\u2014"
    },
    {
      "day": "Tue",
      "date": "2026-04-28",
      "recovery": null,
      "key_event": "\u2014"
    },
    {
      "day": "Wed",
      "date": "2026-04-29",
      "recovery": null,
      "key_event": "\u2014"
    },
    {
      "day": "Thu",
      "date": "2026-04-30",
      "recovery": null,
      "key_event": "\u2014"
    }
  ],
  "daily_macros": {
    "2026-04-24": {
      "cal": null,
      "protein": null,
      "carb": null,
      "fat": null
    },
    "2026-04-25": {
      "cal": 1135,
      "protein": 90,
      "carb": 68,
      "fat": 58
    },
    "2026-04-26": {
      "cal": 1080,
      "protein": 38,
      "carb": 182,
      "fat": 22
    },
    "2026-04-27": {
      "cal": 545,
      "protein": 39,
      "carb": 80,
      "fat": 8
    },
    "2026-04-28": {
      "cal": null,
      "protein": null,
      "carb": null,
      "fat": null
    },
    "2026-04-29": {
      "cal": 605,
      "protein": 69,
      "carb": 34,
      "fat": 20
    },
    "2026-04-30": {
      "cal": 1035,
      "protein": 54,
      "carb": 108,
      "fat": 44
    }
  },
  "blood_baselines": {
    "TSH": {
      "value": 6.654,
      "date": "Mar '26",
      "date_iso": "2026-03-01",
      "status": "high",
      "unit": "\u00b5IU/mL",
      "range_text": "0.4\u20134.78"
    },
    "Free T3": {
      "value": 2.92,
      "date": "Mar '26",
      "date_iso": "2026-03-01",
      "status": "in_range",
      "unit": "pg/mL",
      "range_text": "2.0\u20134.4"
    },
    "Free T4": {
      "value": 1.11,
      "date": "Mar '26",
      "date_iso": "2026-03-01",
      "status": "in_range",
      "unit": "ng/dL",
      "range_text": "0.89\u20131.76"
    },
    "Total T3": {
      "value": 134.0,
      "date": "May '25",
      "date_iso": "2025-05-01",
      "status": "in_range",
      "unit": "ng/dL",
      "range_text": "60\u2013181"
    },
    "Total T4": {
      "value": 7.92,
      "date": "May '25",
      "date_iso": "2025-05-01",
      "status": "in_range",
      "unit": "\u00b5g/dL",
      "range_text": "4.5\u201312.0"
    },
    "Anti-TPO": {
      "value": 354.6,
      "date": "Mar '26",
      "date_iso": "2026-03-01",
      "status": "high",
      "unit": "IU/mL",
      "range_text": "<60"
    },
    "Anti-TG": {
      "value": 13.6,
      "date": "Mar '26",
      "date_iso": "2026-03-01",
      "status": "high",
      "unit": "IU/mL",
      "range_text": "<4.5"
    },
    "TSH Receptor Ab": {
      "value": 3.11,
      "date": "May '25",
      "date_iso": "2025-05-01",
      "status": "high",
      "unit": "IU/L",
      "range_text": "<1.75"
    },
    "Total Testosterone": {
      "value": 205.0,
      "date": "Nov '25",
      "date_iso": "2025-11-01",
      "status": "low",
      "unit": "ng/dL",
      "range_text": "249\u2013836"
    },
    "Free Testosterone": {
      "value": 16.8,
      "date": "Nov '25",
      "date_iso": "2025-11-01",
      "status": "in_range",
      "unit": "pg/mL",
      "range_text": "15\u201350"
    },
    "DHEAS": {
      "value": 293.0,
      "date": "Nov '25",
      "date_iso": "2025-11-01",
      "status": "in_range",
      "unit": "\u00b5g/dL",
      "range_text": "88.9\u2013427"
    },
    "PSA (Total)": {
      "value": 0.619,
      "date": "Apr '22",
      "date_iso": "2022-04-01",
      "status": null,
      "unit": "ng/mL",
      "range_text": "\u22642.0"
    },
    "Glucose Fasting": {
      "value": 99.0,
      "date": "Jan '26",
      "date_iso": "2026-01-01",
      "status": "in_range",
      "unit": "mg/dL",
      "range_text": "70\u2013100"
    },
    "Glucose PP": {
      "value": 103.0,
      "date": "Jan '26",
      "date_iso": "2026-01-01",
      "status": "in_range",
      "unit": "mg/dL",
      "range_text": "<140"
    },
    "HbA1c": {
      "value": 5.6,
      "date": "Jan '26",
      "date_iso": "2026-01-01",
      "status": "in_range",
      "unit": "%",
      "range_text": "<5.7"
    },
    "Insulin Fasting": {
      "value": 13.0,
      "date": "Jan '26",
      "date_iso": "2026-01-01",
      "status": "in_range",
      "unit": "\u00b5IU/mL",
      "range_text": "2\u201325"
    },
    "Insulin PP": {
      "value": 45.1,
      "date": "Jan '26",
      "date_iso": "2026-01-01",
      "status": "in_range",
      "unit": "\u00b5IU/mL",
      "range_text": "<140"
    },
    "C-Peptide": {
      "value": 2.94,
      "date": "Jan '26",
      "date_iso": "2026-01-01",
      "status": null,
      "unit": "ng/mL",
      "range_text": ""
    },
    "Fructosamine": {
      "value": 251.3,
      "date": "May '25",
      "date_iso": "2025-05-01",
      "status": null,
      "unit": "\u00b5mol/L",
      "range_text": ""
    },
    "Homocysteine": {
      "value": 8.48,
      "date": "Jan '26",
      "date_iso": "2026-01-01",
      "status": "in_range",
      "unit": "\u00b5mol/L",
      "range_text": "<15"
    },
    "Total Cholesterol": {
      "value": 223.0,
      "date": "Jan '26",
      "date_iso": "2026-01-01",
      "status": "high",
      "unit": "mg/dL",
      "range_text": "<200"
    },
    "LDL Cholesterol": {
      "value": 156.6,
      "date": "Jan '26",
      "date_iso": "2026-01-01",
      "status": "high",
      "unit": "mg/dL",
      "range_text": "<100"
    },
    "HDL Cholesterol": {
      "value": 41.0,
      "date": "Jan '26",
      "date_iso": "2026-01-01",
      "status": "in_range",
      "unit": "mg/dL",
      "range_text": ">40"
    },
    "Triglycerides": {
      "value": 127.0,
      "date": "Jan '26",
      "date_iso": "2026-01-01",
      "status": null,
      "unit": "mg/dL",
      "range_text": ""
    },
    "VLDL": {
      "value": 25.4,
      "date": "Jan '26",
      "date_iso": "2026-01-01",
      "status": null,
      "unit": "mg/dL",
      "range_text": ""
    },
    "Non-HDL Cholesterol": {
      "value": 182.0,
      "date": "Jan '26",
      "date_iso": "2026-01-01",
      "status": null,
      "unit": "mg/dL",
      "range_text": ""
    },
    "TC/HDL Ratio": {
      "value": 5.4,
      "date": "Jan '26",
      "date_iso": "2026-01-01",
      "status": null,
      "unit": "\u2014",
      "range_text": ""
    },
    "LDL/HDL Ratio": {
      "value": 3.8,
      "date": "Jan '26",
      "date_iso": "2026-01-01",
      "status": null,
      "unit": "\u2014",
      "range_text": ""
    },
    "Lp(a)": {
      "value": 14.6,
      "date": "Nov '25",
      "date_iso": "2025-11-01",
      "status": "in_range",
      "unit": "mg/dL",
      "range_text": "<30"
    },
    "LP-PLA2": {
      "value": 128.0,
      "date": "May '25",
      "date_iso": "2025-05-01",
      "status": null,
      "unit": "nmol/min/mL",
      "range_text": ""
    },
    "ApoA1": {
      "value": 147.0,
      "date": "Nov '25",
      "date_iso": "2025-11-01",
      "status": null,
      "unit": "mg/dL",
      "range_text": ""
    },
    "ApoB": {
      "value": 132.0,
      "date": "Nov '25",
      "date_iso": "2025-11-01",
      "status": "in_range",
      "unit": "mg/dL",
      "range_text": "56\u2013145"
    },
    "ALT (SGPT)": {
      "value": 39.0,
      "date": "Jan '26",
      "date_iso": "2026-01-01",
      "status": "in_range",
      "unit": "U/L",
      "range_text": "<41"
    },
    "AST (SGOT)": {
      "value": 26.0,
      "date": "Jan '26",
      "date_iso": "2026-01-01",
      "status": "in_range",
      "unit": "U/L",
      "range_text": "<40"
    },
    "ALP": {
      "value": 86.0,
      "date": "Jan '26",
      "date_iso": "2026-01-01",
      "status": "in_range",
      "unit": "U/L",
      "range_text": "40\u2013129"
    },
    "GGT": {
      "value": 42.0,
      "date": "Jan '26",
      "date_iso": "2026-01-01",
      "status": "in_range",
      "unit": "U/L",
      "range_text": "<73"
    },
    "Bilirubin Total": {
      "value": 0.94,
      "date": "Jan '26",
      "date_iso": "2026-01-01",
      "status": "in_range",
      "unit": "mg/dL",
      "range_text": "0\u20131.2"
    },
    "Bilirubin Direct": {
      "value": 0.35,
      "date": "Jan '26",
      "date_iso": "2026-01-01",
      "status": "high",
      "unit": "mg/dL",
      "range_text": "0\u20130.3"
    },
    "Bilirubin Indirect": {
      "value": 0.59,
      "date": "Jan '26",
      "date_iso": "2026-01-01",
      "status": "in_range",
      "unit": "mg/dL",
      "range_text": "0\u20131.0"
    },
    "LDH": {
      "value": 165.0,
      "date": "Jan '26",
      "date_iso": "2026-01-01",
      "status": "in_range",
      "unit": "U/L",
      "range_text": "120\u2013250"
    },
    "Total Protein": {
      "value": 7.7,
      "date": "Jan '26",
      "date_iso": "2026-01-01",
      "status": "in_range",
      "unit": "gm/dL",
      "range_text": "5.7\u20138.2"
    },
    "Albumin": {
      "value": 4.5,
      "date": "Jan '26",
      "date_iso": "2026-01-01",
      "status": "in_range",
      "unit": "gm/dL",
      "range_text": "3.2\u20135.2"
    },
    "Globulin": {
      "value": 3.2,
      "date": "Jan '26",
      "date_iso": "2026-01-01",
      "status": "in_range",
      "unit": "gm/dL",
      "range_text": "2.3\u20133.6"
    },
    "A/G Ratio": {
      "value": 1.4,
      "date": "Jan '26",
      "date_iso": "2026-01-01",
      "status": "in_range",
      "unit": "\u2014",
      "range_text": "1.1\u20132.2"
    },
    "Creatinine": {
      "value": 0.77,
      "date": "Jan '26",
      "date_iso": "2026-01-01",
      "status": "in_range",
      "unit": "mg/dL",
      "range_text": "0.67\u20131.2"
    },
    "BUN": {
      "value": 16.8,
      "date": "Jan '26",
      "date_iso": "2026-01-01",
      "status": "in_range",
      "unit": "mg/dL",
      "range_text": "6\u201320"
    },
    "Urea": {
      "value": 36.0,
      "date": "Jan '26",
      "date_iso": "2026-01-01",
      "status": "in_range",
      "unit": "mg/dL",
      "range_text": "15\u201348"
    },
    "Uric Acid": {
      "value": 5.6,
      "date": "Jan '26",
      "date_iso": "2026-01-01",
      "status": "in_range",
      "unit": "mg/dL",
      "range_text": "3.4\u20137.0"
    },
    "eGFR": {
      "value": 114.0,
      "date": "Jan '26",
      "date_iso": "2026-01-01",
      "status": "in_range",
      "unit": "mL/min/1.73m\u00b2",
      "range_text": ">90"
    },
    "Cystatin C": {
      "value": 0.81,
      "date": "May '25",
      "date_iso": "2025-05-01",
      "status": null,
      "unit": "mg/L",
      "range_text": "\u22641.03"
    },
    "Hemoglobin": {
      "value": 15.4,
      "date": "Jan '26",
      "date_iso": "2026-01-01",
      "status": "in_range",
      "unit": "g/dL",
      "range_text": "13\u201317.5"
    },
    "RBC": {
      "value": 5.04,
      "date": "Jan '26",
      "date_iso": "2026-01-01",
      "status": "in_range",
      "unit": "mill/\u00b5L",
      "range_text": "4.4\u20136.0"
    },
    "Hematocrit (PCV)": {
      "value": 46.4,
      "date": "Jan '26",
      "date_iso": "2026-01-01",
      "status": "in_range",
      "unit": "%",
      "range_text": "40\u201352"
    },
    "MCV": {
      "value": 92.0,
      "date": "Jan '26",
      "date_iso": "2026-01-01",
      "status": "in_range",
      "unit": "fL",
      "range_text": "82\u2013101"
    },
    "MCH": {
      "value": 30.5,
      "date": "Jan '26",
      "date_iso": "2026-01-01",
      "status": "in_range",
      "unit": "pg",
      "range_text": "27\u201334"
    },
    "MCHC": {
      "value": 33.2,
      "date": "Jan '26",
      "date_iso": "2026-01-01",
      "status": "in_range",
      "unit": "g/dL",
      "range_text": "31.5\u201336"
    },
    "RDW": {
      "value": 12.7,
      "date": "Jan '26",
      "date_iso": "2026-01-01",
      "status": "in_range",
      "unit": "%",
      "range_text": "11.5\u201314"
    },
    "WBC": {
      "value": 6.58,
      "date": "Jan '26",
      "date_iso": "2026-01-01",
      "status": "in_range",
      "unit": "x10\u00b3/\u00b5L",
      "range_text": "4\u201310.3"
    },
    "Neutrophils %": {
      "value": 50.5,
      "date": "Jan '26",
      "date_iso": "2026-01-01",
      "status": "in_range",
      "unit": "%",
      "range_text": "40\u201380"
    },
    "Lymphocytes %": {
      "value": 36.8,
      "date": "Jan '26",
      "date_iso": "2026-01-01",
      "status": "in_range",
      "unit": "%",
      "range_text": "20\u201340"
    },
    "Monocytes %": {
      "value": 6.5,
      "date": "Jan '26",
      "date_iso": "2026-01-01",
      "status": "in_range",
      "unit": "%",
      "range_text": "2\u201310"
    },
    "Eosinophils %": {
      "value": 6.1,
      "date": "Jan '26",
      "date_iso": "2026-01-01",
      "status": "high",
      "unit": "%",
      "range_text": "0\u20136"
    },
    "Basophils %": {
      "value": 0.1,
      "date": "Jan '26",
      "date_iso": "2026-01-01",
      "status": "in_range",
      "unit": "%",
      "range_text": "0\u20132"
    },
    "Platelet Count": {
      "value": 306.0,
      "date": "Jan '26",
      "date_iso": "2026-01-01",
      "status": "in_range",
      "unit": "x10\u00b3/\u00b5L",
      "range_text": "150\u2013440"
    },
    "MPV": {
      "value": 11.1,
      "date": "Jan '26",
      "date_iso": "2026-01-01",
      "status": "high",
      "unit": "fL",
      "range_text": "7.5\u201311"
    },
    "ESR": {
      "value": 22.0,
      "date": "Jan '26",
      "date_iso": "2026-01-01",
      "status": "high",
      "unit": "mm/hr",
      "range_text": "0\u201315"
    },
    "Serum Iron": {
      "value": 119.0,
      "date": "Jan '26",
      "date_iso": "2026-01-01",
      "status": "in_range",
      "unit": "\u00b5g/dL",
      "range_text": "65\u2013175"
    },
    "TIBC": {
      "value": 329.0,
      "date": "Jan '26",
      "date_iso": "2026-01-01",
      "status": "in_range",
      "unit": "\u00b5g/dL",
      "range_text": "250\u2013450"
    },
    "Transferrin Saturation": {
      "value": 36.0,
      "date": "Jan '26",
      "date_iso": "2026-01-01",
      "status": "in_range",
      "unit": "%",
      "range_text": "12\u201345"
    },
    "Ferritin": {
      "value": 51.3,
      "date": "Jan '26",
      "date_iso": "2026-01-01",
      "status": "in_range",
      "unit": "ng/mL",
      "range_text": "22\u2013400"
    },
    "UIBC": {
      "value": 210.0,
      "date": "Jan '26",
      "date_iso": "2026-01-01",
      "status": "in_range",
      "unit": "\u00b5g/dL",
      "range_text": "125\u2013345"
    },
    "Vitamin D (25-OH)": {
      "value": 46.6,
      "date": "Jan '26",
      "date_iso": "2026-01-01",
      "status": "in_range",
      "unit": "ng/mL",
      "range_text": "30\u2013100"
    },
    "Vitamin B12": {
      "value": 411.0,
      "date": "Jan '26",
      "date_iso": "2026-01-01",
      "status": "in_range",
      "unit": "pg/mL",
      "range_text": "197\u2013771"
    },
    "Vitamin A": {
      "value": 668.38,
      "date": "May '25",
      "date_iso": "2025-05-01",
      "status": "in_range",
      "unit": "ng/mL",
      "range_text": "300\u2013800"
    },
    "Vitamin E": {
      "value": 10844.0,
      "date": "May '25",
      "date_iso": "2025-05-01",
      "status": "in_range",
      "unit": "ng/mL",
      "range_text": "5500\u201318000"
    },
    "Vitamin K": {
      "value": 0.17,
      "date": "May '25",
      "date_iso": "2025-05-01",
      "status": "in_range",
      "unit": "ng/mL",
      "range_text": "0.13\u20131.19"
    },
    "Vitamin B1 (Thiamin)": {
      "value": 0.78,
      "date": "May '25",
      "date_iso": "2025-05-01",
      "status": "in_range",
      "unit": "ng/mL",
      "range_text": "0.5\u20134.0"
    },
    "Vitamin B2 (Riboflavin)": {
      "value": 9.77,
      "date": "May '25",
      "date_iso": "2025-05-01",
      "status": "in_range",
      "unit": "ng/mL",
      "range_text": "1.6\u201368.2"
    },
    "Vitamin B3 (Nicotinic)": {
      "value": 1.38,
      "date": "May '25",
      "date_iso": "2025-05-01",
      "status": "in_range",
      "unit": "ng/mL",
      "range_text": "0.3\u20139.8"
    },
    "Vitamin B5 (Pantothenic)": {
      "value": 73.74,
      "date": "May '25",
      "date_iso": "2025-05-01",
      "status": "in_range",
      "unit": "ng/mL",
      "range_text": "11\u2013150"
    },
    "Vitamin B6 (P5P)": {
      "value": 13.24,
      "date": "May '25",
      "date_iso": "2025-05-01",
      "status": "in_range",
      "unit": "ng/mL",
      "range_text": "5\u201350"
    },
    "Vitamin B7 (Biotin)": {
      "value": 3.79,
      "date": "May '25",
      "date_iso": "2025-05-01",
      "status": "high",
      "unit": "ng/mL",
      "range_text": "0.2\u20133"
    },
    "Vitamin B9 (Folic Acid)": {
      "value": 0.49,
      "date": "May '25",
      "date_iso": "2025-05-01",
      "status": "in_range",
      "unit": "ng/mL",
      "range_text": "0.2\u201320"
    },
    "Sodium": {
      "value": 144.0,
      "date": "Jan '26",
      "date_iso": "2026-01-01",
      "status": "in_range",
      "unit": "mmol/L",
      "range_text": "136\u2013145"
    },
    "Potassium": {
      "value": 5.1,
      "date": "Jan '26",
      "date_iso": "2026-01-01",
      "status": "in_range",
      "unit": "mmol/L",
      "range_text": "3.5\u20135.1"
    },
    "Chloride": {
      "value": 104.0,
      "date": "Jan '26",
      "date_iso": "2026-01-01",
      "status": "in_range",
      "unit": "mmol/L",
      "range_text": "98\u2013107"
    },
    "Calcium": {
      "value": 10.1,
      "date": "Jan '26",
      "date_iso": "2026-01-01",
      "status": "in_range",
      "unit": "mg/dL",
      "range_text": "8.5\u201310.2"
    },
    "Magnesium": {
      "value": 1.9,
      "date": "Jan '26",
      "date_iso": "2026-01-01",
      "status": "in_range",
      "unit": "mg/dL",
      "range_text": "1.6\u20132.6"
    },
    "Phosphorus": {
      "value": 4.3,
      "date": "Jan '26",
      "date_iso": "2026-01-01",
      "status": "in_range",
      "unit": "mg/dL",
      "range_text": "2.4\u20135.1"
    },
    "Bicarbonate": {
      "value": 24.4,
      "date": "Jun '23",
      "date_iso": "2023-06-01",
      "status": "in_range",
      "unit": "mmol/L",
      "range_text": "20\u201331"
    },
    "Selenium": {
      "value": 198.86,
      "date": "May '25",
      "date_iso": "2025-05-01",
      "status": "high",
      "unit": "\u00b5g/L",
      "range_text": "70\u2013150"
    },
    "hs-CRP": {
      "value": 1.545,
      "date": "Jan '26",
      "date_iso": "2026-01-01",
      "status": "in_range",
      "unit": "mg/L",
      "range_text": "<3.0"
    },
    "Anti-CCP (ACCP)": {
      "value": 0.5,
      "date": "May '25",
      "date_iso": "2025-05-01",
      "status": "in_range",
      "unit": "U/mL",
      "range_text": "<5"
    },
    "ANA": {
      "value": 7.16,
      "date": "May '25",
      "date_iso": "2025-05-01",
      "status": "in_range",
      "unit": "AU/mL",
      "range_text": "<50"
    },
    "Alpha-1-Antitrypsin": {
      "value": 126.7,
      "date": "May '25",
      "date_iso": "2025-05-01",
      "status": "in_range",
      "unit": "mg/dL",
      "range_text": "90\u2013200"
    },
    "Amylase": {
      "value": 64.4,
      "date": "May '25",
      "date_iso": "2025-05-01",
      "status": "in_range",
      "unit": "U/L",
      "range_text": "28\u2013100"
    },
    "Lipase": {
      "value": 27.8,
      "date": "May '25",
      "date_iso": "2025-05-01",
      "status": "in_range",
      "unit": "U/L",
      "range_text": "5.6\u201351.3"
    },
    "EHEC (Enterohemorrhagic E. coli)": {
      "value": 8.79,
      "date": "May 2025",
      "date_iso": "2025-05-01",
      "status": "high",
      "unit": "",
      "range_text": "<1e3"
    },
    "Blastocystis hominis": {
      "value": 2.7,
      "date": "May 2025",
      "date_iso": "2025-05-01",
      "status": "high",
      "unit": "",
      "range_text": "<2e3"
    },
    "Bacteroides fragilis": {
      "value": 2.17,
      "date": "May 2025",
      "date_iso": "2025-05-01",
      "status": "in_range",
      "unit": "",
      "range_text": "1.6e9\u20132.5e11"
    },
    "Bifidobacterium spp.": {
      "value": 6.3,
      "date": "May 2025",
      "date_iso": "2025-05-01",
      "status": "low",
      "unit": "",
      "range_text": ">6.7e7"
    },
    "Enterococcus spp.": {
      "value": 3.61,
      "date": "May 2025",
      "date_iso": "2025-05-01",
      "status": "in_range",
      "unit": "",
      "range_text": "1.9e5\u20132.0e8"
    },
    "Escherichia spp.": {
      "value": 6.19,
      "date": "May 2025",
      "date_iso": "2025-05-01",
      "status": "high",
      "unit": "",
      "range_text": "3.7e6\u20133.8e9"
    },
    "Lactobacillus spp.": {
      "value": 7.43,
      "date": "May 2025",
      "date_iso": "2025-05-01",
      "status": "low",
      "unit": "",
      "range_text": "8.6e5\u20136.2e8"
    },
    "Enterobacter spp.": {
      "value": 6.41,
      "date": "May 2025",
      "date_iso": "2025-05-01",
      "status": "high",
      "unit": "",
      "range_text": "1.0e6\u20135.0e7"
    },
    "Akkermansia muciniphila": {
      "value": 1.0,
      "date": "May 2025",
      "date_iso": "2025-05-01",
      "status": "in_range",
      "unit": "",
      "range_text": "1e1\u20138.2e6"
    },
    "Faecalibacterium prausnitzii": {
      "value": 2.21,
      "date": "May 2025",
      "date_iso": "2025-05-01",
      "status": "in_range",
      "unit": "",
      "range_text": "1e3\u20135e8"
    },
    "Roseburia spp.": {
      "value": 1.62,
      "date": "May 2025",
      "date_iso": "2025-05-01",
      "status": "low",
      "unit": "",
      "range_text": "5e7\u20132e10"
    },
    "Pseudomonas spp.": {
      "value": 1.22,
      "date": "May 2025",
      "date_iso": "2025-05-01",
      "status": "high",
      "unit": "",
      "range_text": "<1e4"
    },
    "Pseudomonas aeruginosa": {
      "value": 4.72,
      "date": "May 2025",
      "date_iso": "2025-05-01",
      "status": "in_range",
      "unit": "",
      "range_text": "<5e2"
    },
    "Klebsiella spp.": {
      "value": 1.56,
      "date": "May 2025",
      "date_iso": "2025-05-01",
      "status": "in_range",
      "unit": "",
      "range_text": "<5e3"
    },
    "Klebsiella pneumoniae": {
      "value": 1.71,
      "date": "May 2025",
      "date_iso": "2025-05-01",
      "status": "in_range",
      "unit": "",
      "range_text": "<5e4"
    },
    "Streptococcus spp.": {
      "value": 9.73,
      "date": "May 2025",
      "date_iso": "2025-05-01",
      "status": "high",
      "unit": "",
      "range_text": "<1e3"
    },
    "Bacillus spp.": {
      "value": 3.61,
      "date": "May 2025",
      "date_iso": "2025-05-01",
      "status": "high",
      "unit": "",
      "range_text": "<1.5e5"
    },
    "Enterococcus faecium": {
      "value": 6.11,
      "date": "May 2025",
      "date_iso": "2025-05-01",
      "status": "high",
      "unit": "",
      "range_text": "<1e4"
    },
    "Staphylococcus aureus": {
      "value": 1.75,
      "date": "May 2025",
      "date_iso": "2025-05-01",
      "status": "in_range",
      "unit": "",
      "range_text": "<5e2"
    },
    "Citrobacter freundii": {
      "value": 4.6,
      "date": "May 2025",
      "date_iso": "2025-05-01",
      "status": "in_range",
      "unit": "",
      "range_text": "<5e5"
    },
    "Fusobacterium spp.": {
      "value": 2.49,
      "date": "May 2025",
      "date_iso": "2025-05-01",
      "status": "high",
      "unit": "",
      "range_text": "<1e8"
    },
    "Prevotella spp.": {
      "value": 5.59,
      "date": "May 2025",
      "date_iso": "2025-05-01",
      "status": "high",
      "unit": "",
      "range_text": "<1e8"
    },
    "Bacteroidetes": {
      "value": 1.61,
      "date": "May 2025",
      "date_iso": "2025-05-01",
      "status": "low",
      "unit": "",
      "range_text": "8.6e11\u20133.3e12"
    },
    "Firmicutes": {
      "value": 6.05,
      "date": "May 2025",
      "date_iso": "2025-05-01",
      "status": "in_range",
      "unit": "",
      "range_text": "5.7e10\u20133.0e11"
    },
    "Firmicutes:Bacteroidetes": {
      "value": 0.37,
      "date": "May 2025",
      "date_iso": "2025-05-01",
      "status": "in_range",
      "unit": "",
      "range_text": "<1.0"
    },
    "Elastase-1": {
      "value": 109.0,
      "date": "May 2025",
      "date_iso": "2025-05-01",
      "status": "low",
      "unit": "",
      "range_text": ">200 \u00b5g/g"
    },
    "\u03b2-Glucuronidase": {
      "value": 2147.0,
      "date": "May 2025",
      "date_iso": "2025-05-01",
      "status": "in_range",
      "unit": "",
      "range_text": "<2486 U/mL"
    },
    "Occult Blood (FIT)": {
      "value": 0.0,
      "date": "May 2025",
      "date_iso": "2025-05-01",
      "status": "in_range",
      "unit": "",
      "range_text": "<10 \u00b5g/g"
    },
    "Secretory IgA": {
      "value": 210.0,
      "date": "May 2025",
      "date_iso": "2025-05-01",
      "status": "low",
      "unit": "",
      "range_text": "510\u20132010 \u00b5g/g"
    },
    "Anti-gliadin IgA": {
      "value": 24.0,
      "date": "May 2025",
      "date_iso": "2025-05-01",
      "status": "in_range",
      "unit": "",
      "range_text": "<175 U/L"
    },
    "Calprotectin": {
      "value": 0.0,
      "date": "May 2025",
      "date_iso": "2025-05-01",
      "status": "in_range",
      "unit": "",
      "range_text": "<173 \u00b5g/g"
    },
    "Eosinophil Activation (EDN)": {
      "value": 0.54,
      "date": "May 2025",
      "date_iso": "2025-05-01",
      "status": "in_range",
      "unit": "",
      "range_text": "<2.34 \u00b5g/g"
    },
    "Zonulin": {
      "value": 22.1,
      "date": "May 2025",
      "date_iso": "2025-05-01",
      "status": "in_range",
      "unit": "",
      "range_text": "<175 ng/g"
    },
    "pH": {
      "value": 6.0,
      "date": "May '25",
      "date_iso": "2025-05-01",
      "status": null,
      "unit": "",
      "range_text": ""
    },
    "Specific Gravity": {
      "value": 1.015,
      "date": "May '25",
      "date_iso": "2025-05-01",
      "status": null,
      "unit": "",
      "range_text": ""
    },
    "Microalbumin": {
      "value": 8.3,
      "date": "May '25",
      "date_iso": "2025-05-01",
      "status": null,
      "unit": "",
      "range_text": ""
    },
    "Urine Creatinine": {
      "value": 65.66,
      "date": "May '25",
      "date_iso": "2025-05-01",
      "status": null,
      "unit": "",
      "range_text": ""
    },
    "Albumin/Creatinine Ratio": {
      "value": 12.6,
      "date": "May '25",
      "date_iso": "2025-05-01",
      "status": null,
      "unit": "",
      "range_text": ""
    }
  },
  "active_conditions": [
    "Hashimoto's Thyroiditis (autoimmune hypothyroidism)",
    "Low Testosterone (Hypogonadism)",
    "Grade I Fatty Liver",
    "MTHFR A1298C Homozygous Mutation",
    "Borderline Insulin Resistance",
    "Radial Nerve Injury (Right Tricep)"
  ],
  "active_meds": [
    "Thyroid (compounded NDT \u2014 Bella Sante)",
    "Retatrutide (GLP-1/GIP/glucagon triple agonist)"
  ],
  "treatment_goals": [
    "TSH",
    "Total Testosterone",
    "Body Weight",
    "Body Fat %",
    "Muscle Mass",
    "Fatty Liver",
    "Gut Health"
  ],
  "active_concerns": [
    "Weight trajectory",
    "HRV",
    "Sleep",
    "Body composition",
    "TSH improvement",
    "Testosterone trajectory",
    "Strength capacity",
    "Retatrutide effects",
    "Liver markers",
    "Insulin resistance"
  ],
  "baselines_30d_90d": {
    "hrv_30d_avg": 40.58,
    "hrv_p5": 22.36,
    "hrv_p95": 51.72,
    "rhr_30d_avg": 64.95,
    "rhr_p5": 61,
    "rhr_p95": 77,
    "recovery_30d_avg": 46.64,
    "recovery_p5": 16,
    "recovery_p95": 85,
    "sleep_total_h_30d_avg": 5.41,
    "sleep_total_h_p5": 3.54,
    "sleep_total_h_p95": 7.17,
    "deep_h_30d_avg": 1.47,
    "deep_h_p5": 0.76,
    "deep_h_p95": 1.94
  },
  "gaps": [
    "No Whoop data for 2026-04-27",
    "No Whoop data for 2026-04-28",
    "No Whoop data for 2026-04-29",
    "No Whoop data for 2026-04-30",
    "No health log for 2026-04-24",
    "No health log for 2026-04-28"
  ],
  "days_since_blood": 120,
  "days_since_thyroid": 61,
  "previous_week_summary": null
};

window.WEEK_DATA = Object.assign({}, PARTIAL_DATA, {
  "verdict": "Supplement protocol compliance was 27% across the 5 logged days, including two days (Sun, Thu) where only the morning thyroid dose was taken. The afternoon T3 — a critical med for an underdosed thyroid (TSH 6.654, 61 days since retest) — was missed Sunday and Thursday, the same days recovery cratered. Whoop coverage also collapsed Mon-Thu. The single highest-leverage move is fixing the afternoon-T3 adherence gap and booking the panel; everything else is downstream.",
  "bodySignals": [
    {
      "title": "Autonomic / Recovery — 3 of 7 days, with caveat",
      "body": "HRV averaged 39.68 ms over the 3 captured days (CV 25.4%, only 1% off the 30-day baseline). RHR 66 bpm, in line. Recovery distribution was 1 red (Sat 24), 1 amber (Sun 41), 1 green (Fri 87) — a 3-day sample. Mon-Thu have no Whoop data — sync/charging issue, not autonomic improvement. Treat the visible numbers as directional only; the dominant signal is the same Fri-green-to-Sat-red collapse seen last week."
    },
    {
      "title": "Sleep architecture — debt rate unchanged, deep slipped",
      "body": "Sleep avg 5.67h, deep 1.46h (just under the 1.5h target), REM 1.63h, cumulative debt 7.0h. The 7.0h figure looks better than last week's 13.7h but is computed over 3 captured nights; per-night debt is the same ~2.3h. Deep sleep dipped below target this measurement set — small in isolation, meaningful given it's the only restorative window in a 5.67h budget."
    },
    {
      "title": "Training Load — 2 visible workouts, mid-week unknown",
      "body": "Strain total 27.4, strain:recovery ratio 0.54 — both deflated by the missing 4 Whoop days. Padel sessions count 2, both in the Fri-Sun window. Friday 87 recovery into Saturday 24 reproduces last week's exact pattern — the autonomic system is still not absorbing same-day high strain on chronic undersleep."
    },
    {
      "title": "Supplements — 27% overall, 80% on critical meds, two near-zero days",
      "body": "Across 5 logged days the protocol ran at 27% compliance (27/100 doses). T3+T4 morning was 5/5 (perfect on the most critical med). Afternoon T3 was 3/5 — missed Sunday and Thursday, both also low-recovery / high-stress days. Sunday (Apr 26) and Thursday (Apr 30) were near-zero supplement days (only morning thyroid taken). 6 supplements were 0/5 across the entire week (Omega 3, Myo+Collagen+EAA, Colostrum, TMG, Zinc, Probiotics, Black seed oil). Logging frequency rose to 5/7 (vs 2/7 last week) but the better visibility surfaced a bigger adherence gap than the prior week's data suggested."
    },
    {
      "title": "Metabolic / Nutrition — protein deficit persists",
      "body": "Protein avg 58g across 5 logged days (target 120g, 0/7 hits) — below last week's 64g number. One alcohol day (Sunday, 2 sake shots, recovery 41). Two protein-shake days (Apr 25, Apr 29) showed up as the higher-protein days; non-shake days fell to ~30-50g. With Total T at 205 and retatrutide active, the under-supply is a lean-mass risk."
    }
  ],
  "connections": [
    {
      "title": "Underdosed thyroid + missed afternoon T3 + flat HRV",
      "whoop": "HRV 39.68 ms (3-day, similar to last week), RHR 66 stable, Sun recovery 41 / Thu Whoop missing",
      "lab": "TSH 6.654 µIU/mL (Mar '26, 61 days old, second consecutive week flagged), Anti-TPO 354.6, Free T3 2.92",
      "nutrition": "Afternoon T3 missed Sun + Thu (3/5 compliance on critical PM dose)",
      "interpretation": "TSH 1.4× upper limit, persistent for 61 days, with 40% of afternoon-T3 doses missed in the visible window. Skipping the PM T3 on a TSH-6.654 baseline is an active TSH-elevating event, not just a missed habit. The morning T3+T4 alone cannot maintain steady-state without the afternoon top-up given Pratik's compounded NDT pharmacokinetics.",
      "action": "Restore afternoon-T3 adherence: set a 3 PM phone alarm and stage the dose visibly. Book the thyroid panel TODAY — third consecutive week flagged."
    },
    {
      "title": "Sunday near-zero supplements + alcohol + recovery 41",
      "whoop": "Sun recovery 41 (amber)",
      "lab": "Grade I fatty liver (ALT 39, GGT 42)",
      "nutrition": "Sun (Apr 26): 1/22 supps taken (only morning T3+T4); 2 sake shots at dinner; 0 protein supplement",
      "interpretation": "Sunday concentrated every recovery-degrading variable: missed afternoon T3, missed evening magnesium/probiotics/glutathione, alcohol, low protein. The 41 recovery is the integral of all of those. This isn't 'a day with one issue'; it's a fully-uncovered day.",
      "action": "Define a Sunday-protection rule: minimum is morning + afternoon thyroid + magnesium + zero alcohol. Treat this as non-negotiable for the next 4 weeks while ALT and GGT clear."
    },
    {
      "title": "Six supplements at 0/5 — protocol drift, not a one-off miss",
      "whoop": "n/a",
      "lab": "Targets affected: liver (Glutathione, Omega 3, Black seed oil), gut (Probiotics, Colostrum, TMG), insulin resistance (Myo inositol + Collagen + EAA), immune (Zinc)",
      "nutrition": "Omega 3, Myo+Collagen+EAA, Colostrum, TMG, Zinc, Probiotics, Black seed oil — taken zero times in the captured 5 days",
      "interpretation": "The afternoon, after-lunch, and after-dinner clusters are systematically dropped. This isn't isolation — it's a habit gap. Each unaddressed cluster maps to a treatment goal: gut microbiome (the May '25 stool panel showed low Bifidobacterium, Lactobacillus, Roseburia + high Streptococcus, Enterobacter), insulin resistance, and fatty liver healing.",
      "action": "Fix the trigger: pre-pack the afternoon and evening pill organizer for the next 7 days and put it on Pratik's desk. If after-dinner is the failure point, move the post-dinner stack to right-after-lunch as a recovery measure."
    },
    {
      "title": "Whoop sync gap Mon-Thu — data infrastructure failure",
      "whoop": "No data for Apr 27, 28, 29, 30 (Mon-Thu)",
      "lab": "n/a",
      "nutrition": "Health log present 4 of those 4 days — gap is Whoop-specific, not a behavioral logging dropout",
      "interpretation": "The strap stopped syncing Apr 27 onwards. Health logging held — capture muscle is intact — so this is hardware, not motivation.",
      "action": "Check Whoop strap battery, charging, and Bluetooth pair tonight. Escalate to Whoop support if hardware. A 4-day blackout makes the dashboard unable to do its job."
    }
  ],
  "actions": [
    {
      "priority": 1,
      "category": "Medical",
      "timeframe": "Tonight",
      "text": "Book thyroid panel (TSH, fT3, fT4, rT3, anti-TPO) — 61 days since last, third consecutive briefing flagging it. Do this before bed."
    },
    {
      "priority": 2,
      "category": "Supplements",
      "timeframe": "Tonight",
      "text": "Set a daily 3 PM phone alarm for afternoon T3. Pre-stage the dose where you'll see it. Missed it 2/5 days this week — both bad-recovery days."
    },
    {
      "priority": 3,
      "category": "Supplements",
      "timeframe": "Tonight",
      "text": "Pre-pack the afternoon + evening pill organizer for the next 7 days; put it on the desk. Six supplements ran 0/5 this week — that's the cluster to capture."
    },
    {
      "priority": 4,
      "category": "Medical",
      "timeframe": "Tonight",
      "text": "Diagnose Whoop sync gap (Apr 27 onward) — check strap battery and Bluetooth pair; escalate to Whoop support if hardware."
    },
    {
      "priority": 5,
      "category": "Nutrition",
      "timeframe": "This week",
      "text": "Floor 120g protein daily — whey shake post-Padel + a second shake mid-afternoon on light-dinner days. Two days hit only when shakes were used."
    },
    {
      "priority": 6,
      "category": "Nutrition",
      "timeframe": "This week",
      "text": "Zero alcohol for 4 weeks — make it absolute. ALT 39 and GGT 42 need a clean window to normalize and the Sunday recovery cost is consistent."
    },
    {
      "priority": 7,
      "category": "Sleep",
      "timeframe": "Tonight",
      "text": "Lights out by 10:30 PM, phone out of the bedroom — until per-night debt drops below 1h."
    },
    {
      "priority": 8,
      "category": "Medical",
      "timeframe": "Within 2 weeks",
      "text": "Schedule full panel — CBC, LFT, lipids, fasting insulin/glucose, hs-CRP. 120 days since last."
    }
  ]
});
